main – KORC
main Program
376 statements
Source File
Uses
korc_types
korc_units
korc_hpc
korc_HDF5
korc_fields
korc_ppusher
korc_interp
korc_collisions
korc_initialize
korc_finalize
korc_profiles
korc_input
korc_fio
Note
Main function of KORC.
The main program contains the calls to the main functions and subroutines. Also, it contains the variables that control the behavior of the core of KORC and all other external/optional modules.
Order of KORC operations
Communication and Timing
1. Parallel Communications
Subroutine initialize_communications in korc_hpc that initializes MPI and OpenMP communications.
2. Timers
Subroutine timing_KORC in korc_hpc that times the execution of any parallel sections of KORC.
Initialization
1. HDF5
Subroutine initialize_HDF5 in korc_HDF5 that initializes HDF5 library.
2. Initialize korc parameters
Subroutine initialize_korc_parameters in korc_initialize that initializes paths and KORC parameters through load_korc_params on MPI processes.
3. Initialize fields
Subroutine initialize_fields in korc_fields that initializes parameters of the EM fields, either analytically or from an external HDF5 file. Reads in &analytical_fields_params and &externalPlasmaModel namelists from input file.
4. Initialize Profiles
Subroutine initialize_profiles in korc_profiles that initializes parameters of the plasma profiles, either analytically or from an external HDF5 file. Reads in &plasmaProfiles namelist from input file. Only initialized if collisions (params%collisions==T) are
5. Initialize Particle Velocity Phase Space
Subroutine initialize_particles in korc_initialize that initializes particle parameters from &amplasma_species namelist, allocates arrays for individual particles, including location, velocity, local EM fields and plasma profiles, etc., and calls initial_energy_pitch_dist to assign particles' energy and pitch angle according to the chosen distribution.
9. Compute Characteristic Plasma Parameters
Subroutine compute_charcs_plasma_params in korc_units calculates the characteristic plasma parameters params%cpp that are used for normalizations. Also finds the maximum non-relativistic and relativistic cyclotron frequencies to be used for setting the timstep for the time-evolution algorithms.
6. Initialize Collision Parameters
Subroutine initialize_collision_params in korc_collisions that initializes collision parameters for the SS (single-species) and MS (multiple-species) data types, reading in namefiles from the KORC input file. MS reads in namelist &CollisionParamsMultipleSpecies while SS reads in namelist &CollisionParamsSingleSpecies.
10. Define Time Step
Subroutine define_time_step in korc_initialize either loads time-stepping parameters for a restart, or defines new parameters based on a maximum timestep set by the inverse of the relativistic cyclotron frequency.
11. Initialize Particle Pusher
12. Normalize Variables
Subroutine normalize_variables in korc_units normalizes variables consistent with characteristic plasma parameters calculated in compute_charcs_plasma_params.
13. Normalize Collision Parameters
Subroutine normalize_collisions_params in korc_collisions that normalizes collision parameters for the SS (single-species) and MS (multiple-species) data types.
14. Define Collision Time Step
Subroutine define_collisions_time_step in korc_collisions that sets subcycling iteration number for collisions based off of the collision frequency model used.
15. Initialize Fields Interpolant
Subroutine initialize_fields_interpolant in korc_interp calls EZspline subroutines EZspline_init for memory allocation and boundary condition setup and EZspline_setup to compute the necessary cubic coefficients needed for subsequent field interpolations. The magnetic field can be defined in terms of an axisymmetric scalar flux function, axisymmetric field, or 3D field, while the electric field can be defined as an axisymmetric or 3D field.
16. Initialize Profiles Interpolant
Subroutine initialize_profiles_interpolant in korc_interp calls EZspline subroutines EZlinear_init for axisymmetric (flux-surface quantities) or EZspline_init for 3D profiles for memory allocation and boundary condition setup and EZspline_setup to compute the necessary cubic coefficients needed for subsequent field interpolations. Only initialized if collisions (params%collisions==T) are present for ne, Te, Zeff
17. Set Particle Initial Conditions
Subroutine set_up_particles_ic in korc_initialize calls subroutines to prescribe initial conditions or load them from file for a restart. Initial spatial values are prescribed with intitial_spatial_distribution in korc_spatial_distribution and initial velocity values are prescribed with initial_gyro_distribution in korc_velocity_distribution.
18. Save Simulation and Collision Parameters
Subroutines save_simulation_parameters in korc_HDF5 and save_collision_params in korc_collisions call subroutines to save simulation and collision parameters.
Calls
Contents
Variables
params spp F P it mpierr
Source Code
main
Variables
Type Attributes Name Initial
type(KORC_PARAMS) :: params
Contains the parameters that control the core of KORC: time steping, output list, etc.
type(SPECIES), DIMENSION(:), ALLOCATABLE :: spp
Contains the initial parameters of each species, which can be different electrons with different distribution functions.
type(FIELDS) :: F
and electric fields, or in the case of using external fields it contains the data used in the interpolations. See korc_fields for details.
type(PROFILES) :: P
or in the case of using external fields it contains the data used in the interpolations. See korc_profiles for details.
integer(kind=ip) :: it
Time iteration
integer :: mpierr
Source Code
program main
  !! @note  Main function of KORC. @endnote
  !! The main program contains the calls to the main functions and subroutines.
  !! Also, it contains the variables that control
  !! the behavior of the core of KORC and all other external/optional modules.
  use korc_types
  use korc_units
  use korc_hpc
  use korc_HDF5
  use korc_fields
  use korc_ppusher
  use korc_interp
  use korc_collisions
  use korc_initialize
  use korc_finalize
  use korc_profiles
  use korc_input
#ifdef FIO
  use korc_fio
#endif
  implicit none
  TYPE(KORC_PARAMS) :: params
  !! Contains the parameters that control the core of KORC:
  !! time steping, output list, etc.
  TYPE(SPECIES), DIMENSION(:), ALLOCATABLE :: spp
  !! Contains the initial parameters of each species, which
  !! can be different electrons with different
  !! distribution functions.
  TYPE(FIELDS) :: F
  !! F: Contains the parameters of the analytical magnetic
  !! and electric fields, or in the case of using
  !! external fields it contains the data used in the interpolations.
  !!See [[korc_fields(module)]] for details.
  TYPE(PROFILES) :: P
  !! P: Contains the parameters of the analytical plasma profiles,
  !! or in the case of using external
  !! fields it contains the data used in the interpolations.
  !! See [[korc_profiles(module)]] for details.
  INTEGER(ip) :: it
  !! Time iteration
  INTEGER                 :: mpierr
  call initialize_communications(params)
  !!<h2>Order of KORC operations</h2>
  !!
  !!<h3>Communication and Timing</h3>
  !! <h4>1\. Parallel Communications</h4>
  !!
  !! Subroutine [[initialize_communications]] in [[korc_hpc]] that
  !! initializes MPI and OpenMP communications.
  if (params%mpi_params%rank .EQ. 0) then
     flush(output_unit_write)
  end if
  call timing_KORC(params)
  !! <h4>2\. Timers</h4>
  !!
  !! Subroutine [[timing_KORC]] in [[korc_hpc]] that times the
  !! execution of any parallel sections of KORC.
  ! * * * INITIALIZATION STAGE * * *!
  if (params%mpi_params%rank .EQ. 0) then
     flush(output_unit_write)
  end if
  call initialize_HDF5()
  !!<h3>Initialization</h3>
  !!
  !! <h4>1\. HDF5</h4>
  !!
  !! Subroutine [[initialize_HDF5]] in [[korc_HDF5]] that initializes
  !! HDF5 library.
  if (params%mpi_params%rank .EQ. 0) then
     flush(output_unit_write)
  end if
  call initialize_korc_parameters(params)
  !! <h4>2\. Initialize korc parameters</h4>
  !!
  !! Subroutine [[initialize_korc_parameters]] in [[korc_initialize]] that
  !! initializes paths and KORC parameters through [[load_korc_params]]
  !! on MPI processes.
  if (params%mpi_params%rank .EQ. 0) then
     flush(output_unit_write)
  end if
  call initialize_fields(params,F)
  !! <h4>3\. Initialize fields</h4>
  !!
  !! Subroutine [[initialize_fields]] in [[korc_fields]] that initializes
  !! parameters of the EM fields, either analytically or from an external HDF5
  !! file. Reads in &amp;analytical_fields_params and
  !! &amp;externalPlasmaModel namelists from input file.
  if (params%mpi_params%rank .EQ. 0) then
     flush(output_unit_write)
  end if
  call initialize_profiles(params,P,F)
  !! <h4>4\. Initialize Profiles</h4>
  !!
  !! Subroutine [[initialize_profiles]] in [[korc_profiles]] that initializes
  !! parameters of the plasma profiles, either analytically or from an
  !! external HDF5
  !! file. Reads in &amp;plasmaProfiles namelist from input file.
  !! Only initialized if collisions (params%collisions==T) are
  if (params%mpi_params%rank .EQ. 0) then
     flush(output_unit_write)
  end if
  call initialize_particles(params,F,P,spp) ! Initialize particles
  !! <h4>5\. Initialize Particle Velocity Phase Space</h4>
  !!
  !! Subroutine [[initialize_particles]] in [[korc_initialize]] that
  !! initializes particle parameters from &amplasma_species namelist,
  !! allocates arrays for individual particles, including location, velocity,
  !! local EM fields and plasma profiles, etc., and
  !! calls [[initial_energy_pitch_dist]] to assign particles' energy and pitch
  !! angle according to the chosen distribution.
!  write(output_unit_write,'("init eta: ",E17.10)') spp(1)%vars%eta
#ifdef FIO
  if (TRIM(params%field_model) .eq. 'M3D_C1') then
     if (params%mpi_params%rank .EQ. 0) then
        write(output_unit_write,*) "* * * * INITIALIZING M3D-C1 INTERFACE * * * *"
     endif
     call initialize_m3d_c1(params, F, P, spp,.true.)
     if (params%mpi_params%rank .EQ. 0) then
        write(output_unit_write,*) "* * * * * * * * * * * * * * * * * * * * * * *"
     endif
  elseif (TRIM(params%field_model) .eq. 'NIMROD') THEN
     if (params%mpi_params%rank .EQ. 0) then
        write(output_unit_write,*) "* * * * INITIALIZING NIMROD INTERFACE * * * *"
     endif
     call initialize_nimrod(params, F, P, spp,.true.)
     if (params%mpi_params%rank .EQ. 0) then
        write(output_unit_write,*) "* * * * * * * * * * * * * * * * * * * * * * *"
     endif
  endif
#endif
  if (params%mpi_params%rank .EQ. 0) then
     flush(output_unit_write)
  end if
  call compute_charcs_plasma_params(params,spp,F)
  !! <h4>9\. Compute Characteristic Plasma Parameters</h4>
  !!
  !! Subroutine [[compute_charcs_plasma_params]] in [[korc_units]] calculates
  !! the characteristic plasma parameters params%cpp that are used for normalizations.
  !! Also finds the maximum non-relativistic and relativistic cyclotron frequencies
  !! to be used for setting the timstep for the time-evolution algorithms.
  call initialize_collision_params(params,spp,P,F,.true.)
  !! <h4>6\. Initialize Collision Parameters</h4>
  !!
  !! Subroutine [[initialize_collision_params]] in [[korc_collisions]] that
  !! initializes collision parameters for the SS (single-species) and MS
  !! (multiple-species) data types, reading in namefiles from the KORC input file.
  !! MS reads in namelist &CollisionParamsMultipleSpecies while SS reads in
  !! namelist &CollisionParamsSingleSpecies.
  call define_time_step(params,F)
  !! <h4>10\. Define Time Step</h4>
  !!
  !! Subroutine [[define_time_step]] in [[korc_initialize]] either loads
  !! time-stepping parameters for a restart, or defines new parameters based
  !! on a maximum timestep
  !! set by the inverse of the relativistic cyclotron frequency.
  if (params%mpi_params%rank .EQ. 0) then
     flush(output_unit_write)
  end if
  call initialize_particle_pusher(params)
  !! <h4>11\. Initialize Particle Pusher</h4>
  if (params%SC_E) then
     call define_SC_time_step(params,F)
  end if
  call normalize_variables(params,spp,F,P)
  !! <h4>12\. Normalize Variables</h4>
  !!
  !! Subroutine [[normalize_variables]] in [[korc_units]] normalizes
  !! variables consistent with characteristic plasma parameters
  !! calculated in [[compute_charcs_plasma_params]].
  call normalize_collisions_params(params)
  !! <h4>13\. Normalize Collision Parameters </h4>
  !!
  !! Subroutine [[normalize_collisions_params]] in [[korc_collisions]] that
  !! normalizes collision parameters for the SS (single-species) and MS
  !! (multiple-species) data types.
  call define_collisions_time_step(params,F,.true.)
  !! <h4>14\. Define Collision Time Step</h4>
  !!
  !! Subroutine [[define_collisions_time_step]] in [[korc_collisions]] that
  !! sets subcycling iteration number for collisions based off of the collision
  !! frequency model used.
  ! *** *** *** *** *** ***   *** *** *** *** *** *** ***
  ! *** BEYOND THIS POINT VARIABLES ARE DIMENSIONLESS ***
  ! *** *** *** *** *** ***   *** *** *** *** *** *** ***
  if (params%mpi_params%rank .EQ. 0) then
     flush(output_unit_write)
  end if
#ifdef PSPLINE
  call initialize_fields_interpolant(params,F)
  !! <h4>15\. Initialize Fields Interpolant</h4>
  !!
  !! Subroutine [[initialize_fields_interpolant]] in [[korc_interp]] calls
  !! EZspline
  !! subroutines EZspline_init for memory allocation and boundary condition
  !! setup
  !! and EZspline_setup to compute the necessary cubic coefficients needed
  !! for subsequent
  !! field interpolations. The magnetic field can be defined in terms of an
  !! axisymmetric
  !! scalar flux function, axisymmetric field, or 3D field, while the
  !! electric field
  !! can be defined as an axisymmetric or 3D field.
  if (params%mpi_params%rank .EQ. 0) then
     flush(output_unit_write)
  end if
  call initialize_profiles_interpolant(params,P)
#endif
  !! <h4>16\. Initialize Profiles Interpolant</h4>
  !!
  !! Subroutine [[initialize_profiles_interpolant]] in [[korc_interp]]
  !! calls EZspline
  !! subroutines EZlinear_init for axisymmetric (flux-surface quantities) or
  !! EZspline_init for 3D profiles for memory allocation and boundary
  !! condition setup
  !! and EZspline_setup to compute the necessary cubic coefficients needed
  !! for subsequent
  !! field interpolations.
  !! Only initialized if collisions (params%collisions==T) are present for
  !! ne, Te, Zeff
  if (params%mpi_params%rank .EQ. 0) then
     flush(output_unit_write)
  end if
  if (params%mpi_params%rank .EQ. 0) then
     write(output_unit_write,'("* * * * INITIALIZING INITIAL CONDITIONS * * * *",/)')
     flush(output_unit_write)
  end if
  call set_up_particles_ic(params,F,spp,P)
  if (params%mpi_params%rank .EQ. 0) then
     write(output_unit_write,'("* * * * * * * * * * * * * * * * * * * * * * * *",/)')
     flush(output_unit_write)
  end if
  !write(6,*) 'V',spp(1)%vars%V
!  write(output_unit_write,'("post ic eta: ",E17.10)') spp(1)%vars%eta
  !! <h4>17\. Set Particle Initial Conditions</h4>
  !!
  !! Subroutine [[set_up_particles_ic]] in [[korc_initialize]] calls
  !! subroutines to prescribe initial conditions or load them
  !! from file for a restart. Initial spatial values are prescribed with
  !! [[intitial_spatial_distribution]] in [[korc_spatial_distribution]] and
  !! initial velocity values are prescribed with [[initial_gyro_distribution]]
  !! in [[korc_velocity_distribution]].
!  if (minval(spp(1)%vars%Y(:,1)).lt.1._rp/params%cpp%length) stop 'error with init'
  ! * * * INITIALIZATION STAGE * * *
  if (params%mpi_params%rank .EQ. 0) then
     flush(output_unit_write)
  end if
!  write(output_unit_write,'("GC init eta: ",E17.10)') spp(1)%vars%eta
  if (.NOT.(params%restart.OR.params%proceed.or.params%reinit)) then
     if (params%orbit_model(1:2).eq.'FO') then
        call FO_init(params,F,spp,.true.,.false.)
     else if (params%orbit_model(1:2).eq.'GC') then
        call GC_init(params,F,spp)
     end if
     if (params%SC_E) then
        if (params%field_model(1:1).eq.'A') then
           call init_SC_E1D(params,F,spp(1))
        else if (params%field_model(1:1).eq.'E') then
           call init_SC_E1D_FS(params,F,spp(1))
        end if
     end if
  else
     call get_fields(params,spp(1)%vars,F)
     if (params%SC_E) then
        if (params%field_model(1:1).eq.'A') then
           call reinit_SC_E1D(params,F)
        else if (params%field_model(1:1).eq.'E') then
           call reinit_SC_E1D_FS(params,F)
        end if
     end if
  end if
  !write(6,*) 'V',spp(1)%vars%V
  !write(6,*) 'eta',spp(1)%vars%eta
!  write(6,*) '1Y_R',spp(1)%vars%Y(1:4,1)*params%cpp%length
  ! * * * SAVING INITIAL CONDITION AND VARIOUS SIMULATION PARAMETERS * * * !
  call save_simulation_parameters(params,spp,F,P)
  call save_collision_params(params)
  !! <h4>18\. Save Simulation and Collision Parameters</h4>
  !!
  !! Subroutines [[save_simulation_parameters]] in [[korc_HDF5]] and
  !! [[save_collision_params]] in [[korc_collisions]] call
  !! subroutines to save simulation and collision parameters.
  if (.NOT.(params%restart.OR.params%proceed.or.params%reinit)) then
     call save_simulation_outputs(params,spp,F) ! Save initial condition
     call save_restart_variables(params,spp,F)
  end if
  ! * * * SAVING INITIAL CONDITION AND VARIOUS SIMULATION PARAMETERS * * * !
!  write(output_unit_write,'("pre ppusher loop eta: ",E17.10)') spp(1)%vars%eta
  call timing_KORC(params)
  if (params%mpi_params%rank .EQ. 0) then
     flush(output_unit_write)
  end if
  if (params%orbit_model(1:2).eq.'FO'.and.((params%field_model(1:3).eq.'ANA') &
       .or.(params%field_model(1:3).eq.'UNI'))) then
     call FO_init(params,F,spp,.false.,.true.)
     ! Initial half-time particle push
     do it=params%ito,params%t_steps,params%t_skip
        call adv_FOeqn_top(params,F,P,spp)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
#ifdef PSPLINE
  if (params%orbit_model(1:2).eq.'FO'.and.params%field_model(1:3).eq.'EXT' &
       .and..not.((params%field_model(10:13).eq.'MARS').or. &
       (params%field_model(10:14).eq.'AORSA'))) then
     call FO_init(params,F,spp,.false.,.true.)
     ! Initial half-time particle push
     do it=params%ito,params%t_steps,params%t_skip
        call adv_FOinterp_top(params,F,P,spp)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
#endif
#ifdef FIO
  if (params%orbit_model(1:2).eq.'FO'.and. &
       (TRIM(params%field_model).eq.'M3D_C1'.or. &
       TRIM(params%field_model).eq.'NIMROD').and. &
       .not.F%ReInterp_2x1t) then
     call FO_init(params,F,spp,.false.,.true.)
     ! Initial half-time particle push
     do it=params%ito,params%t_steps,params%t_skip
        call adv_FOfio_top(params,F,P,spp)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'FO'.and. &
       (params%field_model.eq.'M3D_C1'.or. &
       TRIM(params%field_model).eq.'NIMROD') &
       .and.F%ReInterp_2x1t) then
     call FO_init(params,F,spp,.false.,.true.)
     ! Initial half-time particle push
     do it=F%ind0_2x1t,params%time_slice
        !write(6,*) it,F%ind0_2x1t
        if (it.gt.F%ind0_2x1t) then
           if (params%field_model.eq.'M3D_C1') then
              call initialize_m3d_c1(params, F, P, spp,.false.)
           else
              call initialize_nimrod(params, F, P, spp,.false.)
           end if
           if (params%collisions) then
              if (params%field_model.eq.'M3D_C1') then
                 call initialize_m3d_c1_imp(params,F,P, &
                      params%num_impurity_species,.false.)
              end if
           end if
        end if
        if (params%mpi_params%rank .EQ. 0) then
           write(output_unit_write,*) 'tskip',params%t_skip
           flush(output_unit_write)
        end if
        call adv_FOfio_top(params,F,P,spp)
        params%it = params%it+params%t_skip
        params%time = params%init_time &
             +REAL(params%it,rp)*params%dt
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
        F%ind_2x1t=F%ind_2x1t+1_ip
        if (params%mpi_params%rank .EQ. 0) then
           write(output_unit_write,*) 'KORC time ',params%time*params%cpp%time
           flush(output_unit_write)
        end if
     end do
  end if
#endif
#ifdef PSPLINE
  if (params%orbit_model(1:2).eq.'FO'.and. &
       params%field_model(10:13).eq.'MARS') then
     call FO_init(params,F,spp,.false.,.true.)
     ! Initial half-time particle push
     do it=params%ito,params%t_steps,params%t_skip
        call adv_FOinterp_mars_top(params,F,P,spp)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'FO'.and. &
       params%field_model(10:14).eq.'AORSA') then
     call FO_init(params,F,spp,.false.,.true.)
     ! Initial half-time particle push
     do it=params%ito,params%t_steps,params%t_skip
        call adv_FOinterp_aorsa_top(params,F,P,spp)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
#endif
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'eqn'.and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip*params%t_it_SC
        call adv_GCeqn_top(params,F,P,spp)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip*params%t_it_SC,rp)*params%dt
        params%it = it-1_ip+params%t_skip*params%t_it_SC
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
        if (params%mpi_params%rank .EQ. 0) then
           flush(output_unit_write)
        end if
     end do
  end if
#ifdef PSPLINE
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
       F%axisymmetric_fields.and.params%field_model(10:12).eq.'PSI'.and. &
       params%SC_E.and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_psi_top_FS(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
       F%axisymmetric_fields.and.(params%field_model(10:12).eq.'PSI'.OR. &
       params%field_model(12:14).eq.'PSI').and. &
       (.not.params%SC_E).and.(.not.F%Dim2x1t).and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_psi_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
       F%axisymmetric_fields.and.(params%field_model(10:12).eq.'PSI'.OR. &
       params%field_model(12:14).eq.'PSI').and. &
       (.not.params%SC_E).and.F%Dim2x1t.and.(.not.F%ReInterp_2x1t).and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_psi2x1t_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and. &
       params%field_eval.eq.'interp'.and. &
       F%axisymmetric_fields.and. &
       (params%field_model(10:12).eq.'PSI'.OR. &
       params%field_model(12:14).eq.'PSI').and. &
       (.not.params%SC_E).and. &
       F%Dim2x1t.and.F%ReInterp_2x1t.and. &
       .not.params%field_model.eq.'M3D_C1') then
     if (params%mpi_params%rank .EQ. 0) then
        write(output_unit_write,*) 'initial 2x1t_ind time',F%X%PHI(F%ind_2x1t)*params%cpp%time
        flush(output_unit_write)
     end if
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_psiwE_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        F%ind_2x1t=F%ind_2x1t+1_ip
        if (params%mpi_params%rank .EQ. 0) then
           write(output_unit_write,*) 'KORC time',params%time*params%cpp%time
           write(output_unit_write,*) '2x1t_ind time',F%X%PHI(F%ind_2x1t)*params%cpp%time
        end if
        call initialize_fields_interpolant(params,F)
        if (params%LargeCollisions) then
           call initialize_collision_params(params,spp,P,F,.false.)
           call define_collisions_time_step(params,F,.false.)
        end if
        call save_restart_variables(params,spp,F)
        if (params%mpi_params%rank .EQ. 0) then
           flush(output_unit_write)
        end if
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
       F%axisymmetric_fields.and.F%dBfield.and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_2DBdB_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
       F%axisymmetric_fields.and.(params%field_model(10:12).eq.'2DB'.or. &
       params%field_model(12:13).eq.'2D').and..not.(F%dBfield).and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_B2D_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
         .not.(F%axisymmetric_fields).and.(F%dBfield).and. &
         (params%field_model(10:14).eq.'3DBdB').and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_3DBdB_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
         .not.(F%axisymmetric_fields).and.(F%dBfield).and. &
         .not.(params%field_model(10:14).eq.'3DBdB').and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_3DBdB1_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
       .not.(F%axisymmetric_fields).and..not.(F%dBfield).and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_B_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
#endif
#ifdef FIO
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_model.eq.'M3D_C1'.and. &
       .not.F%ReInterp_2x1t) then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_fio_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip*params%t_it_SC,rp)*params%dt
        params%it = it-1_ip+params%t_skip*params%t_it_SC
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
        if (params%mpi_params%rank .EQ. 0) then
           flush(output_unit_write)
        end if
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_model.eq.'M3D_C1'.and. &
       F%ReInterp_2x1t) then
     do it=F%ind0_2x1t,params%time_slice
!        write(6,*) it,F%ind0_2x1t
        if (it.gt.F%ind0_2x1t) then
           call initialize_m3d_c1(params, F, P, spp,.false.)
           if (params%collisions.or.params%radiation) then
              call initialize_m3d_c1_imp(params,F,P, &
                   params%num_impurity_species,.false.)
           end if
        end if
        if (params%mpi_params%rank .EQ. 0) then
           write(output_unit_write,*) 'tskip',params%t_skip
           flush(output_unit_write)
        end if
        call adv_GCinterp_fio_top(params,spp,P,F)
        params%it = params%it+params%t_skip
        params%time = params%init_time &
             +REAL(params%it,rp)*params%dt
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
        !comment out for debugging only
        F%ind_2x1t=F%ind_2x1t+1_ip
        if (params%mpi_params%rank .EQ. 0) then
           write(output_unit_write,*) 'KORC time ',params%time*params%cpp%time
           flush(output_unit_write)
        end if
     end do
  end if
#endif
  call timing_KORC(params)
  ! * * * FINALIZING SIMULATION * * *
  call finalize_HDF5()
#ifdef PSPLINE
  call finalize_interpolants(params)
#endif
#ifdef FIO
  if (TRIM(params%field_model) .eq. 'M3D_C1'.or. &
      TRIM(params%field_model) .eq. 'NIMROD') then
     call finalize_FIO(params,F,P)
  end if
#endif
  ! DEALLOCATION OF VARIABLES
  call deallocate_variables(params,F,P,spp)
  call deallocate_collisions_params(params)
  call finalize_communications(params)
  ! * * * FINALIZING SIMULATION * * *
  if (params%mpi_params%rank .EQ. 0) then
     write(output_unit_write,'("KORC ran successfully!")')
     close(output_unit_write)
  end if
end program main
Call graph
main calls adv_gcinterp_psi_top, adv_fointerp_top, save_simulation_parameters, save_collision_params, initialize_particles, adv_gcinterp_psi2x1t_top, compute_charcs_plasma_params, adv_gcinterp_3dbdb_top, set_up_particles_ic, reinit_sc_e1d_fs, deallocate_variables, adv_fofio_top, finalize_fio, adv_fointerp_mars_top, initialize_hdf5, define_collisions_time_step, adv_gcinterp_b_top, initialize_nimrod, gc_init, initialize_profiles, adv_gcinterp_2dbdb_top, adv_gceqn_top, initialize_profiles_interpolant, timing_korc, initialize_m3d_c1, normalize_collisions_params, deallocate_collisions_params, save_simulation_outputs, reinit_sc_e1d, initialize_korc_parameters, adv_foeqn_top, initialize_collision_params, adv_fointerp_aorsa_top, adv_gcinterp_3dbdb1_top, define_time_step, normalize_variables, define_sc_time_step, initialize_communications, initialize_m3d_c1_imp, finalize_interpolants, finalize_communications, initialize_fields, adv_gcinterp_psi_top_fs, save_restart_variables, fo_init, finalize_hdf5, adv_gcinterp_fio_top, initialize_fields_interpolant, initialize_particle_pusher, adv_gcinterp_b2d_top, adv_gcinterp_psiwe_top
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, calculate_gcfields_p, advance_fpinterp_vars
adv_fointerp_top calls interp_fo3dfields_p, advance_fp3dinterp_vars, advance_fointerp_vars, interp_fofields1_p, cart_to_cyl_p, interp_fofields_p
save_simulation_parameters calls save_1d_array_to_hdf5, h5gclose_f, h5eset_auto_f, rsave_2d_array_to_hdf5, save_to_hdf5, save_string_parameter, h5fclose_f, rsave_3d_array_to_hdf5
save_collision_params calls save_params_ss, save_params_ms
initialize_particles calls sigmaz, zo, spong_w, ro, eo_lims, eno, initial_energy_pitch_dist, spong_b, dr, phio, spong_dlam, xtrace, dz, sigmar
adv_gcinterp_psi2x1t_top calls calculate_gcfields_2x1t_p, advance_fpinterp_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
set_up_particles_ic calls intitial_spatial_distribution, float, initial_gyro_distribution, load_particles_ic, init_random_seed
reinit_sc_e1d_fs calls initialize_sc1d_field_interpolant_fs
deallocate_variables calls deallocate_fields_arrays, deallocate_profiles_arrays
adv_fofio_top calls advance_fp3dinterp_vars, get_fio_vector_potential_p, get_fio_foelectric_fields_p, get_fio_fomagnetic_fields_p, advance_fofio_vars, cart_to_cyl_p
finalize_fio calls fio_close_field, fio_close_source
adv_fointerp_mars_top calls advance_fointerp_vars, interp_fofields_mars_p, cart_to_cyl_p
initialize_hdf5 calls h5tcopy_f, h5open_f, h5tget_size_f
define_collisions_time_step calls nu_d_fio, korc_abort, nu_s_fio, float, nu_s, nu_d, nu_par
adv_gcinterp_b_top calls advance_fpinterp_vars
initialize_nimrod calls korc_abort, fio_set_int_option, fio_allocate_search_hint, fio_get_field, fio_close_field, fio_get_options, fio_open_source, fio_eval_field, fio_close_source, load_prev_iter
gc_init calls cross, add_analytical_e_p, deg2rad
initialize_profiles calls allocate_2d_profiles_arrays, load_profiles_data_from_hdf5
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gceqn_top calls calculate_sc_e1d, include_coulombcollisions_gc_p, calculate_sc_p, analytical_fields_bmag_p, rad2deg
initialize_profiles_interpolant calls ezspline_error, ezspline_setup, ezspline_init
timing_korc calls mpi_gather, mpi_barrier, mpi_wtime
initialize_m3d_c1 calls fio_set_int_option, fio_get_real_field_parameter, fio_allocate_search_hint, fio_get_field, fio_close_field, fio_get_options, fio_open_source, fio_eval_field, load_prev_iter
normalize_collisions_params calls normalize_params_ms, normalize_params_ss
deallocate_collisions_params calls deallocate_params_ms
save_simulation_outputs calls save_1d_array_to_hdf5, h5gclose_f, rsave_2d_array_to_hdf5, h5fclose_f
reinit_sc_e1d calls initialize_sc1d_field_interpolant
initialize_korc_parameters calls load_korc_params, mpi_barrier, read_namelist
adv_foeqn_top calls analytical_fields_p, advance_fp3deqn_vars, advance_foeqn_vars, uniform_fields_p
initialize_collision_params calls initialize_m3d_c1_imp, korc_abort, load_params_ss, load_params_ms
adv_fointerp_aorsa_top calls advance_fointerp_vars, interp_fofields_aorsa_p, cart_to_cyl_p
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
define_time_step calls load_time_stepping_params, load_prev_time, float
initialize_communications calls initialize_mpi, omp_get_num_procs, omp_get_num_threads
initialize_m3d_c1_imp calls fio_set_int_option, fio_get_field, fio_close_field, fio_make_species, fio_get_options
finalize_interpolants calls ezspline_allocated
finalize_communications calls finalize_mpi
initialize_fields calls allocate_1d_fs_arrays, initialize_gc_fields_3d, allocate_2d_fields_arrays, korc_abort, load_1d_fs_from_hdf5, initialize_gc_fields, load_field_data_from_hdf5, allocate_3d_fields_arrays, load_prev_iter, load_dim_data_from_hdf5, which_fields_in_file
adv_gcinterp_psi_top_fs calls calculate_sc_e1d_fs, calculate_sc_p_fs, advance_fpinterp_vars
save_restart_variables calls save_1d_array_to_hdf5, h5gclose_f, rsave_2d_array_to_hdf5, save_to_hdf5, mpi_gather, mpi_barrier, h5fclose_f
fo_init calls analytical_fields_p, interp_fo3dfields_p, get_fio_vector_potential_p, get_fio_foelectric_fields_p, interp_fofields1_p, get_fio_fomagnetic_fields_p, interp_fofields_aorsa_p, uniform_fields_p, interp_fofields_mars_p, cart_to_cyl_p, interp_fofields_p
finalize_hdf5 calls h5close_f
adv_gcinterp_fio_top calls omp_get_thread_num
initialize_fields_interpolant calls ezspline_allocated, ezspline_error, ezspline_setup, ezspline_init
adv_gcinterp_b2d_top calls advance_fpinterp_vars
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p, korc_abort, calculate_gcfields_p, omp_get_thread_num
analytical_fields_p calls cart_to_tor_check_if_confined_p
interp_fo3dfields_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
nu_d_fio calls cb_ee, cb_ei_fio
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
calculate_sc_e1d calls initialize_sc1d_field_interpolant, mpi_allreduce
get_fio_vector_potential_p calls fio_eval_field
get_fio_foelectric_fields_p calls fio_eval_field
save_1d_array_to_hdf5 calls isave_1d_array_to_hdf5, rsave_1d_array_to_hdf5
advance_fointerp_vars calls radiation_force_p, include_coulombcollisions_fo_p
initialize_mpi calls mpi_barrier, mpi_reduce, mpi_init, mpi_initialized, mpi_comm_size, set_paths, mpi_abort, mpi_bcast, mpi_comm_rank, mpi_cart_create
load_time_stepping_params calls korc_abort, h5fclose_f, h5fopen_f, mpi_bcast, load_from_hdf5
interp_fofields1_p calls ezspline_error, calculate_magnetic_field_p, ezspline_interp, check_if_in_fields_domain_p
initialize_sc1d_field_interpolant_fs calls ezspline_allocated, ezspline_error, ezspline_setup, ezspline_init
initial_energy_pitch_dist calls mpi_barrier
calculate_gcfields_2x1t_p calls ezspline_error, ezspline_derivative, check_if_in_fields_domain_p
rsave_2d_array_to_hdf5 calls h5screate_simple_f, h5dclose_f, h5dwrite_f, h5sclose_f
allocate_1d_fs_arrays calls h5fclose_f, h5fopen_f, load_from_hdf5
get_fio_fomagnetic_fields_p calls fio_eval_field
save_to_hdf5 calls rsave_to_hdf5, i1save_to_hdf5, i8save_to_hdf5, i2save_to_hdf5, i4save_to_hdf5
allocate_2d_fields_arrays calls allocate_v_field_2dx, allocate_v_field_2d
intitial_spatial_distribution calls korc_abort
nu_s_fio calls cf_fio
include_coulombcollisions_gc_p calls calculate_gcfields_2x1t_p, add_analytical_e_p, calculate_gcfields_p, calculate_gcfieldswe_p, dca_sd, interp_fields_3d_p, get_random, analytical_profiles_p, interp_hcollision_p, cb_ei_sd, interp_fields_p, cb_ee_sd, calculate_gcfields_p_fs, interp_focollision_p, analytical_fields_gc_p, calculate_2dbdbfields_p, cb_ei_sd_fio, cf_sd_fio, ca_sd, cf_sd
advance_fofio_vars calls radiation_force_p, include_coulombcollisions_fofio_p
korc_abort calls mpi_abort
save_string_parameter calls h5tcopy_f, h5dwrite_vl_f, h5screate_simple_f, h5tset_strpad_f, h5dclose_f, h5sclose_f
interp_fofields_aorsa_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
load_prev_time calls korc_abort, h5fclose_f, h5fopen_f, mpi_bcast, mpi_comm_rank, load_from_hdf5
advance_foeqn_vars calls radiation_force_p, include_coulombcollisions_fo_p
load_1d_fs_from_hdf5 calls h5fclose_f, h5fopen_f, load_array_from_hdf5
calculate_sc_e1d_fs calls initialize_sc1d_field_interpolant_fs, mpi_allreduce
save_params_ss calls h5gclose_f, save_to_hdf5, save_string_parameter, h5fclose_f
load_profiles_data_from_hdf5 calls allocate_2d_profiles_arrays, h5fclose_f, h5fopen_f, allocate_3d_profiles_arrays, load_array_from_hdf5, load_from_hdf5
initialize_sc1d_field_interpolant calls ezspline_allocated, ezspline_error, ezspline_setup, ezspline_init
load_field_data_from_hdf5 calls h5fclose_f, h5fopen_f, load_array_from_hdf5, load_from_hdf5
nu_s calls cf
nu_d calls cb_ei, cb_ee
allocate_3d_fields_arrays calls allocate_v_field_3d
finalize_mpi calls mpi_barrier, mpi_finalized, mpi_finalize
calculate_gcfields_p calls ezspline_error, ezspline_derivative, check_if_in_fields_domain_p
rsave_3d_array_to_hdf5 calls h5screate_simple_f, h5dclose_f, h5dwrite_f, h5sclose_f
advance_fpinterp_vars calls include_coulombcollisions_gc_p
read_namelist calls korc_abort, mpi_barrier, rmcoment
load_prev_iter calls korc_abort, h5fclose_f, h5fopen_f, mpi_bcast, load_from_hdf5
load_params_ss calls vte_wu, clogee_wu, gammac_wu, clogei_wu
interp_fofields_mars_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
load_particles_ic calls korc_abort, mpi_barrier, h5fclose_f, h5fopen_f, load_array_from_hdf5, mpi_scatter
interp_fofields_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
load_params_ms calls zj_mult, gammac_wu, zo_mult
save_params_ms calls save_1d_array_to_hdf5, h5gclose_f, save_to_hdf5, save_string_parameter, h5fclose_f
load_dim_data_from_hdf5 calls h5fclose_f, h5fopen_f, load_from_hdf5
which_fields_in_file calls h5fclose_f, h5fopen_f
nu_par calls ca
isave_1d_array_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5dclose_f, h5dwrite_f, h5sclose_f, h5awrite_f, h5tset_size_f, h5aclose_f, h5acreate_f
calculate_gcfieldswe_p calls ezspline_error, ezspline_derivative, check_if_in_fields_domain_p
clogee_wu calls vte_wu, clog0_wu
dca_sd calls psi, vte, gammacee
interp_fields_3d_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
get_random calls omp_get_thread_num, random_get_number
rsave_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5dclose_f, h5dwrite_f, h5sclose_f, h5awrite_f, h5tset_size_f, h5aclose_f, h5acreate_f
gammac_wu calls clogee_wu
interp_hcollision_p calls ezspline_error, ezspline_interp, check_if_in_profiles_domain_p
i1save_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5dclose_f, h5sclose_f, h5awrite_f, h5tset_size_f, h5aclose_f, h5acreate_f
set_paths calls korc_abort
i8save_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5dclose_f, h5sclose_f, h5awrite_f, h5tset_size_f, h5aclose_f, h5acreate_f
cb_ei_sd calls clogei, clogee, g_j, vte, gammacee
calculate_magnetic_field_p calls ezspline_error, ezspline_interp, ezspline_gradient
interp_fields_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
cb_ee_sd calls psi, delta, vte, gammacee
cb_ei calls clogei, clogee, g_j
cf_fio calls psi, clogee, h_j
i2save_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5dclose_f, h5sclose_f, h5awrite_f, h5tset_size_f, h5aclose_f, h5acreate_f
calculate_gcfields_p_fs calls ezspline_error, ezspline_derivative, check_if_in_fields_domain_p
cb_ee calls psi
interp_focollision_p calls ezspline_error, ezspline_interp, check_if_in_profiles_domain_p
cf calls psi, clogee, h_j
include_coulombcollisions_fo_p calls cart_to_cyl_p, dca_sd, get_random, analytical_profiles_p, cb_ei_sd, cb_ee_sd, interp_focollision_p, ca_sd, cf_sd, unitvectors_p
load_array_from_hdf5 calls rload_1d_array_from_hdf5, rload_3d_array_from_hdf5, rload_2d_array_from_hdf5
calculate_2dbdbfields_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
cb_ei_sd_fio calls clogei, clogee, g_j, vte, gammacee
cb_ei_fio calls clogei, clogee, g_j
clogei_wu calls vte_wu, clog0_wu
rsave_1d_array_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5dclose_f, h5dwrite_f, h5sclose_f, h5awrite_f, h5tset_size_f, h5aclose_f, h5acreate_f
ca calls psi
cf_sd_fio calls psi, clogee, h_j, vte, gammacee
ca_sd calls psi, vte, gammacee
i4save_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5dclose_f, h5sclose_f, h5awrite_f, h5tset_size_f, h5aclose_f, h5acreate_f
cf_sd calls psi, clogee, h_j, vte, gammacee
include_coulombcollisions_fofio_p calls cart_to_cyl_p, dca_sd, get_random, cb_ei_sd, cb_ee_sd, ca_sd, cf_sd, unitvectors_p, get_fio_ion_p, get_fio_profile_p
load_from_hdf5 calls rload_from_hdf5, iload_from_hdf5
get_fio_ion_p calls fio_eval_field
clogei calls vte, clog0
rload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
clogee calls vte, clog0
rload_1d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
get_fio_profile_p calls fio_eval_field
rload_3d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
delta calls vte
iload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
gammacee calls clogee
rload_2d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f