add_interp_SCE_p_FS – KORC
add_interp_SCE_p_FS Subroutine
14 statements
Source File
public subroutine add_interp_SCE_p_FS(params, F, PSIp, E_PHI)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
type(FIELDS), intent(in) :: F
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: PSIp
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: E_PHI
Calls
Called by
Contents
Source Code
add_interp_SCE_p_FS
Source Code
subroutine add_interp_SCE_p_FS(params,F,PSIp,E_PHI)
  TYPE(KORC_PARAMS), INTENT(IN)                              :: params
  TYPE(FIELDS), INTENT(IN)                               :: F
  REAL(rp), DIMENSION(params%pchunk), INTENT(IN)      :: PSIp
  REAL(rp), DIMENSION(params%pchunk), INTENT(INOUT)      :: E_PHI
  REAL(rp),DIMENSION(params%pchunk) :: E_SC_PHI
  INTEGER :: cc,pchunk
  pchunk=params%pchunk
  call EZspline_interp(efield_SC1d%PHI,pchunk, PSIp, E_SC_PHI, ezerr)
  call EZspline_error(ezerr)
  !$OMP SIMD
  do cc=1_idef,pchunk
     E_PHI(cc)=E_PHI(cc)+E_SC_PHI(cc)
  end do
  !$OMP END SIMD
end subroutine add_interp_SCE_p_FS
Call graph
add_interp_sce_p_fs calls ezspline_interp, ezspline_error
advance_gcinterp_psi_vars_fs calls add_interp_sce_p_fs