adv_GCinterp_psi_top_FS – KORC
adv_GCinterp_psi_top_FS Subroutine
89 statements
Source File
public subroutine adv_GCinterp_psi_top_FS(params, spp, P, F)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(inout) :: params
Core KORC simulation parameters.
type(SPECIES), intent(inout), DIMENSION(:), ALLOCATABLE :: spp
An instance of the derived type SPECIES containing all the parameters and simulation variables of the different species in the simulation.
type(PROFILES), intent(in) :: P
type(FIELDS), intent(inout) :: F
Calls
Called by
Contents
Source Code
adv_GCinterp_psi_top_FS
Source Code
  subroutine adv_GCinterp_psi_top_FS(params,spp,P,F)
    TYPE(KORC_PARAMS), INTENT(INOUT)                           :: params
    !! Core KORC simulation parameters.
    TYPE(PROFILES), INTENT(IN)                                 :: P
    TYPE(FIELDS), INTENT(INOUT)                                   :: F
    TYPE(SPECIES), DIMENSION(:), ALLOCATABLE, INTENT(INOUT)    :: spp
    !! An instance of the derived type SPECIES containing all the parameters
    !! and simulation variables of the different species in the simulation.
    REAL(rp), DIMENSION(params%pchunk)               :: Bmag
    REAL(rp),DIMENSION(params%pchunk) :: Y_R,Y_PHI,Y_Z
    REAL(rp),DIMENSION(params%pchunk) :: B_R,B_PHI,B_Z
    REAL(rp),DIMENSION(params%pchunk) :: E_R,E_PHI,E_Z
    REAL(rp),DIMENSION(params%pchunk) :: ne,Te,Zeff
    REAL(rp),DIMENSION(params%pchunk) :: V_PLL,V_MU
    REAL(rp),DIMENSION(params%pchunk) :: PSIp
    REAL(rp),DIMENSION(params%pchunk) :: curlb_R,curlb_PHI,curlb_Z
    REAL(rp),DIMENSION(params%pchunk) :: gradB_R,gradB_PHI,gradB_Z
    INTEGER(is),DIMENSION(params%pchunk) :: flagCon,flagCol
    REAL(rp) :: m_cache,q_cache,B0,EF0,R0,q0,lam,ar
    INTEGER                                                    :: ii
    !! Species iterator.
    INTEGER                                                    :: pp
    !! Particles iterator.
    INTEGER                                                    :: cc,pchunk
    !! Chunk iterator.
    INTEGER(ip)                                                    :: tt
    INTEGER(ip)                                                    :: ttt
    !! time iterator.
    real(rp),dimension(F%dim_1D) :: Vden,Vdenave,VdenOMP
    !! time iterator.
    do ii = 1_idef,params%num_species
       pchunk=params%pchunk
       q_cache=spp(ii)%q
       m_cache=spp(ii)%m
       do ttt=1_ip,params%t_it_SC
          VdenOMP=0._rp
          !$OMP PARALLEL DO default(none) &
          !$OMP& FIRSTPRIVATE(q_cache,m_cache,pchunk) &
          !$OMP& SHARED(params,ii,spp,P,F) &
          !$OMP& PRIVATE(pp,tt,Bmag,cc,Y_R,Y_PHI,Y_Z,V_PLL,V_MU,B_R,B_PHI,B_Z, &
          !$OMP& flagCon,flagCol,E_PHI,PSIp,curlb_R,curlb_PHI,curlb_Z, &
          !$OMP& gradB_R,gradB_PHI,gradB_Z,ne, &
          !$OMP& Vden,Vdenave) &
          !$OMP& REDUCTION(+:VdenOMP)
          do pp=1_idef,spp(ii)%ppp,pchunk
             !          write(output_unit_write,'("pp: ",I16)') pp
             !$OMP SIMD
             do cc=1_idef,pchunk
                Y_R(cc)=spp(ii)%vars%Y(pp-1+cc,1)
                Y_PHI(cc)=spp(ii)%vars%Y(pp-1+cc,2)
                Y_Z(cc)=spp(ii)%vars%Y(pp-1+cc,3)
                V_PLL(cc)=spp(ii)%vars%V(pp-1+cc,1)
                V_MU(cc)=spp(ii)%vars%V(pp-1+cc,2)
                PSIp(cc)=spp(ii)%vars%PSI_P(pp-1+cc)
                flagCon(cc)=spp(ii)%vars%flagCon(pp-1+cc)
                flagCol(cc)=spp(ii)%vars%flagCol(pp-1+cc)
             end do
             !$OMP END SIMD
             if (.not.params%FokPlan) then
                Vdenave=0._rp
                do tt=1_ip,params%t_skip
                   call advance_GCinterp_psi_vars_FS(spp(ii)%vars,pp,tt, &
                        params, &
                        Y_R,Y_PHI,Y_Z,V_PLL,V_MU,q_cache,m_cache,flagCon,flagCol, &
                        F,P,B_R,B_PHI,B_Z,E_PHI,PSIp,curlb_R,curlb_PHI, &
                        curlb_Z,gradB_R,gradB_PHI,gradB_Z)
                   call calculate_SC_p_FS(params,F,B_R,B_PHI,B_Z,PSIp, &
                        V_PLL,V_MU,m_cache,flagCon,flagCol,Vden)
                   !                   write(output_unit_write,*) 'pre-Vdenave',Vdenave(F%dim_1D)
                   Vdenave=(Vdenave*REAL(tt-1_ip)+Vden)/REAL(tt)
                   !                   write(output_unit_write,*) 'Vden',Vden(F%dim_1D)
                   !                   write(output_unit_write,*) 'post-Vdenave',Vdenave(F%dim_1D)
                   !                   if (pp.eq.9_idef) write(output_unit_write,*) 'Vdenave',Vdenave(F%dim_1D)
                end do !timestep iterator
                !                write(output_unit_write,*) 'Vdenave',Vdenave(F%dim_1D)
                VdenOMP=VdenOMP+Vdenave
                !                write(output_unit_write,*) 'VdenOMP',VdenOMP(F%dim_1D)
                !$OMP SIMD
                do cc=1_idef,pchunk
                   spp(ii)%vars%Y(pp-1+cc,1)=Y_R(cc)
                   spp(ii)%vars%Y(pp-1+cc,2)=Y_PHI(cc)
                   spp(ii)%vars%Y(pp-1+cc,3)=Y_Z(cc)
                   spp(ii)%vars%V(pp-1+cc,1)=V_PLL(cc)
                   spp(ii)%vars%V(pp-1+cc,2)=V_MU(cc)
                   spp(ii)%vars%flagCon(pp-1+cc)=flagCon(cc)
                   spp(ii)%vars%flagCol(pp-1+cc)=flagCol(cc)
                   spp(ii)%vars%B(pp-1+cc,1) = B_R(cc)
                   spp(ii)%vars%B(pp-1+cc,2) = B_PHI(cc)
                   spp(ii)%vars%B(pp-1+cc,3) = B_Z(cc)
                   spp(ii)%vars%gradB(pp-1+cc,1) = gradB_R(cc)
                   spp(ii)%vars%gradB(pp-1+cc,2) = gradB_PHI(cc)
                   spp(ii)%vars%gradB(pp-1+cc,3) = gradB_Z(cc)
                   spp(ii)%vars%curlb(pp-1+cc,1) = curlb_R(cc)
                   spp(ii)%vars%curlb(pp-1+cc,2) = curlb_PHI(cc)
                   spp(ii)%vars%curlb(pp-1+cc,3) = curlb_Z(cc)
                   spp(ii)%vars%E(pp-1+cc,2) = E_PHI(cc)
                   spp(ii)%vars%PSI_P(pp-1+cc) = PSIp(cc)
                end do
                !$OMP END SIMD
             else
                call advance_FPinterp_vars(params,Y_R,Y_PHI, &
                     Y_Z,V_PLL,V_MU,m_cache,flagCon,flagCol,F,P,E_PHI,ne,PSIp)
                !$OMP SIMD
                do cc=1_idef,pchunk
                   spp(ii)%vars%V(pp-1+cc,1)=V_PLL(cc)
                   spp(ii)%vars%V(pp-1+cc,2)=V_MU(cc)
                   spp(ii)%vars%flagCol(pp-1+cc)=flagCol(cc)
                   spp(ii)%vars%E(pp-1+cc,2) = E_PHI(cc)
                end do
                !$OMP END SIMD
             end if
             !$OMP SIMD
             do cc=1_idef,pchunk
                B_R(cc)=spp(ii)%vars%B(pp-1+cc,1)
                B_PHI(cc)=spp(ii)%vars%B(pp-1+cc,2)
                B_Z(cc)=spp(ii)%vars%B(pp-1+cc,3)
                Bmag(cc)=sqrt(B_R(cc)*B_R(cc)+B_PHI(cc)*B_PHI(cc)+B_Z(cc)*B_Z(cc))
                spp(ii)%vars%g(pp-1+cc)=sqrt(1+V_PLL(cc)**2+ &
                     2*V_MU(cc)*Bmag(cc))
                spp(ii)%vars%eta(pp-1+cc) = atan2(sqrt(2*m_cache*Bmag(cc)* &
                     spp(ii)%vars%V(pp-1+cc,2)),spp(ii)%vars%V(pp-1+cc,1))* &
                     180.0_rp/C_PI
             end do
             !$OMP END SIMD
          end do !particle chunk iterator
          !$OMP END PARALLEL DO
          !write(output_unit_write,*) 'VdenOMP',VdenOMP(F%dim_1D)
          call calculate_SC_E1D_FS(params,F,VdenOMP)
       end do
    end do !species iterator
  end subroutine adv_GCinterp_psi_top_FS
Call graph
adv_gcinterp_psi_top_fs calls calculate_sc_e1d_fs, calculate_sc_p_fs, advance_fpinterp_vars
calculate_sc_e1d_fs calls mpi_allreduce, initialize_sc1d_field_interpolant_fs
advance_fpinterp_vars calls include_coulombcollisions_gc_p
include_coulombcollisions_gc_p calls calculate_gcfieldswe_p, dca_sd, interp_fields_3d_p, get_random, calculate_gcfields_p, analytical_profiles_p, interp_hcollision_p, cb_ei_sd, interp_fields_p, calculate_gcfields_p_fs, interp_focollision_p, analytical_fields_gc_p, calculate_2dbdbfields_p, cb_ei_sd_fio, cf_sd_fio, ca_sd, calculate_gcfields_2x1t_p, add_analytical_e_p, cf_sd, cb_ee_sd
initialize_sc1d_field_interpolant_fs calls ezspline_allocated, ezspline_error, ezspline_init, ezspline_setup
calculate_gcfieldswe_p calls ezspline_error, check_if_in_fields_domain_p, ezspline_derivative
dca_sd calls psi, vte, gammacee
interp_fields_3d_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
get_random calls omp_get_thread_num, random_get_number
calculate_gcfields_p calls ezspline_error, check_if_in_fields_domain_p, ezspline_derivative
interp_hcollision_p calls ezspline_error, ezspline_interp, check_if_in_profiles_domain_p
cb_ei_sd calls vte, clogei, g_j, gammacee, clogee
interp_fields_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
calculate_gcfields_p_fs calls ezspline_error, check_if_in_fields_domain_p, ezspline_derivative
interp_focollision_p calls ezspline_error, ezspline_interp, check_if_in_profiles_domain_p
calculate_2dbdbfields_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
cb_ei_sd_fio calls vte, clogei, g_j, gammacee, clogee
cf_sd_fio calls psi, vte, gammacee, clogee, h_j
ca_sd calls psi, vte, gammacee
calculate_gcfields_2x1t_p calls ezspline_error, check_if_in_fields_domain_p, ezspline_derivative
cf_sd calls psi, vte, gammacee, clogee, h_j
cb_ee_sd calls psi, vte, gammacee, delta
clogei calls vte, clog0
gammacee calls clogee
clogee calls vte, clog0
delta calls vte
main calls adv_gcinterp_psi_top_fs