advance_FPeqn_vars – KORC
advance_FPeqn_vars Subroutine
15 statements
Source File
public subroutine advance_FPeqn_vars(params, Y_R, Y_PHI, Y_Z, V_PLL, V_MU, flagCon, flagCol, m_cache, F, P, PSIp)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(inout) :: params
Core KORC simulation parameters.
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: Y_R
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: Y_PHI
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: Y_Z
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: V_PLL
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: V_MU
integer(kind=is), intent(inout), DIMENSION(params%pchunk) :: flagCon
integer(kind=is), intent(inout), DIMENSION(params%pchunk) :: flagCol
real(kind=rp), intent(in) :: m_cache
type(FIELDS), intent(in) :: F
type(PROFILES), intent(in) :: P
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: PSIp
Calls
Contents
Source Code
advance_FPeqn_vars
Source Code
  subroutine advance_FPeqn_vars(params,Y_R,Y_PHI,Y_Z,V_PLL,V_MU,flagCon,flagCol, &
       m_cache,F,P,PSIp)
    TYPE(PROFILES), INTENT(IN)                                 :: P
    TYPE(FIELDS), INTENT(IN)                                   :: F
    TYPE(KORC_PARAMS), INTENT(INOUT)                              :: params
    !! Core KORC simulation parameters.
    INTEGER(ip)                                                    :: tt
    !! time iterator.
    REAL(rp),DIMENSION(params%pchunk), INTENT(INOUT)  :: Y_R,Y_PHI,Y_Z
    REAL(rp),DIMENSION(params%pchunk), INTENT(INOUT)  :: V_PLL,V_MU,PSIp
    REAL(rp),DIMENSION(params%pchunk)  :: E_PHI
    INTEGER(is),DIMENSION(params%pchunk), INTENT(INOUT)  :: flagCon,flagCol
    REAL(rp),intent(in) :: m_cache
    REAL(rp),DIMENSION(params%pchunk) :: ne
    do tt=1_ip,params%t_skip
       call include_CoulombCollisions_GC_p(tt,params,Y_R,Y_PHI,Y_Z, &
            V_PLL,V_MU,m_cache,flagCon,flagCol,F,P,E_PHI,ne,PSIp)
       !       write(output_unit_write,'("Collision Loop in FP")')
    end do
  end subroutine advance_FPeqn_vars
Call graph
advance_fpeqn_vars calls include_coulombcollisions_gc_p
include_coulombcollisions_gc_p calls calculate_gcfieldswe_p, dca_sd, interp_fields_3d_p, get_random, calculate_gcfields_p, analytical_profiles_p, interp_hcollision_p, cb_ei_sd, interp_fields_p, calculate_gcfields_p_fs, interp_focollision_p, analytical_fields_gc_p, calculate_2dbdbfields_p, cb_ei_sd_fio, cf_sd_fio, ca_sd, calculate_gcfields_2x1t_p, add_analytical_e_p, cf_sd, cb_ee_sd
calculate_gcfieldswe_p calls ezspline_error, check_if_in_fields_domain_p, ezspline_derivative
dca_sd calls psi, vte, gammacee
interp_fields_3d_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
get_random calls omp_get_thread_num, random_get_number
calculate_gcfields_p calls ezspline_error, check_if_in_fields_domain_p, ezspline_derivative
interp_hcollision_p calls ezspline_error, ezspline_interp, check_if_in_profiles_domain_p
cb_ei_sd calls vte, clogei, g_j, gammacee, clogee
interp_fields_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
calculate_gcfields_p_fs calls ezspline_error, check_if_in_fields_domain_p, ezspline_derivative
interp_focollision_p calls ezspline_error, ezspline_interp, check_if_in_profiles_domain_p
calculate_2dbdbfields_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
cb_ei_sd_fio calls vte, clogei, g_j, gammacee, clogee
cf_sd_fio calls psi, vte, gammacee, clogee, h_j
ca_sd calls psi, vte, gammacee
calculate_gcfields_2x1t_p calls ezspline_error, check_if_in_fields_domain_p, ezspline_derivative
cf_sd calls psi, vte, gammacee, clogee, h_j
cb_ee_sd calls psi, vte, gammacee, delta
clogei calls vte, clog0
gammacee calls clogee
clogee calls vte, clog0
delta calls vte