bessik – KORC
bessik Subroutine
126 statements
Source File
public subroutine bessik(x, xnu, ri, rk, rip, rkp)
Uses
nrtype
nrutil
nr
@brief Subroutine taken from "Numerical Recipes" that calculates the modified Bessel function of
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in) :: x
real(kind=SP), intent(in) :: xnu
real(kind=SP), intent(out) :: ri
real(kind=SP), intent(out) :: rk
real(kind=SP), intent(out) :: rip
real(kind=SP), intent(out) :: rkp
Calls
Contents
Source Code
bessik
Source Code
        SUBROUTINE bessik(x,xnu,ri,rk,rip,rkp)
        USE nrtype
        REAL(SP), INTENT(IN) :: x,xnu
        REAL(SP), INTENT(OUT) :: ri,rk,rip,rkp
        END SUBROUTINE bessik
Call graph
bessik calls assert, beschb
assert calls assert_v, assert3, assert1, assert4, assert2