besselk – KORC
besselk Function
8 statements
Source File
public function besselk(v, x)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: v
real(kind=rp), intent(in) :: x
Return Value real(kind=rp)
Called by
Contents
Source Code
besselk
Source Code
  FUNCTION besselk(v,x)
    REAL(rp) :: besselk
    REAL(rp), INTENT(IN) :: x
    REAL(rp), INTENT(IN) :: v
    REAL(4) :: ri,rk,rip,rkp
    call bessik(REAL(x,4),REAL(v,4),ri,rk,rip,rkp)
    besselk = REAL(rk,rp)
  END FUNCTION besselk
Call graph
intbesselk calls besselk
p_integral calls intbesselk
pr calls p_integral
frexpr calls pr
fre_hxpr calls pr