CB_ei_FIO – KORC
CB_ei_FIO Function
17 statements
Source File
private function CB_ei_FIO(params, v)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
real(kind=rp), intent(in) :: v
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
CB_ei_FIO
Source Code
  function CB_ei_FIO(params,v)
    TYPE(KORC_PARAMS), INTENT(IN)     :: params
    REAL(rp), INTENT(IN)     :: v
    REAL(rp)                 :: CB_ei_FIO
    REAL(rp)                 :: CB_ei_temp
    REAL(rp)                 :: x
    INTEGER :: i
    x = v/cparams_ss%VTe
    CB_ei_FIO  = (0.5_rp*cparams_ss%Gammac/v)*(cparams_ss%Zeff* &
         CLogei(v,cparams_ss%ne,cparams_ss%Te)/ &
         CLogee(v,cparams_ss%ne,cparams_ss%Te))
    if (params%bound_electron_model.eq.'HESSLOW') then
       CB_ei_temp=CB_ei_FIO
       do i=1,1
          CB_ei_temp=CB_ei_temp+CB_ei_FIO*cparams_ms%nz(i)/(cparams_ms%ne* &
               cparams_ss%Zeff*CLogei(v,cparams_ss%ne,cparams_ss%Te))* &
               g_j(i,v)
       end do
       CB_ei_FIO=CB_ei_temp
    end if
  end function CB_ei_FIO
Call graph
cb_ei_fio calls clogei, clogee, g_j
clogei calls clog0, vte
clogee calls clog0, vte
nu_d_fio calls cb_ei_fio
define_collisions_time_step calls nu_d_fio
main calls define_collisions_time_step