CB_ei_SD_FIO – KORC
CB_ei_SD_FIO Function
21 statements
Source File
public function CB_ei_SD_FIO(params, v, ne, Te, nimp, Zeff)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
real(kind=rp), intent(in) :: v
real(kind=rp), intent(in) :: ne
real(kind=rp), intent(in) :: Te
real(kind=rp), intent(in), DIMENSION(cparams_ms%num_impurity_species) :: nimp
real(kind=rp), intent(in) :: Zeff
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
CB_ei_SD_FIO
Source Code
  function CB_ei_SD_FIO(params,v,ne,Te,nimp,Zeff)
    TYPE(KORC_PARAMS), INTENT(IN)     :: params
    REAL(rp), INTENT(IN)     :: v
    REAL(rp), INTENT(IN)     :: ne
    REAL(rp), INTENT(IN)     :: Te
    REAL(rp), INTENT(IN)     :: Zeff
    REAL(rp), DIMENSION(cparams_ms%num_impurity_species), INTENT(IN)     :: nimp
    REAL(rp)                 :: CB_ei_SD_FIO
    REAL(rp)                 :: CB_ei_temp
    REAL(rp)                 :: x
    INTEGER :: i
    x = v/VTe(Te)
    CB_ei_SD_FIO  = (0.5_rp*Gammacee(v,ne,Te)/v)* &
         (Zeff*CLogei(v,ne,Te)/CLogee(v,ne,Te))
    if (params%bound_electron_model.eq.'HESSLOW') then
       CB_ei_temp=CB_ei_SD_FIO
       do i=1,cparams_ms%num_impurity_species
          CB_ei_temp=CB_ei_temp+CB_ei_SD_FIO*nimp(i)/(ne* &
               Zeff*CLogei(v,ne,Te))*g_j(i,v)
       end do
       CB_ei_SD_FIO=CB_ei_temp
    end if
  end function CB_ei_SD_FIO
Call graph
cb_ei_sd_fio calls vte, clogei, g_j, gammacee, clogee
clogei calls vte, clog0
gammacee calls clogee
clogee calls vte, clog0
include_coulombcollisionsla_gc_p calls cb_ei_sd_fio
include_coulombcollisions_gcfio_p calls cb_ei_sd_fio
include_coulombcollisions_gc_p calls cb_ei_sd_fio
advance_fpeqn_vars calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, advance_fpinterp_vars
advance_gcinterp_fio_vars calls include_coulombcollisions_gcfio_p
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
adv_gceqn_top calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
main calls adv_gcinterp_psi_top, adv_gcinterp_psiwe_top, adv_gceqn_top, adv_gcinterp_psi_top_fs, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_gcinterp_3dbdb_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_b2d_top
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars