CF_SD_FIO – KORC
CF_SD_FIO Function
21 statements
Source File
public function CF_SD_FIO(params, v, ne, Te, nimp)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
real(kind=rp), intent(in) :: v
real(kind=rp), intent(in) :: ne
real(kind=rp), intent(in) :: Te
real(kind=rp), intent(in), DIMENSION(cparams_ms%num_impurity_species) :: nimp
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
CF_SD_FIO
Source Code
  function CF_SD_FIO(params,v,ne,Te,nimp)
    TYPE(KORC_PARAMS), INTENT(IN)     :: params
    REAL(rp), INTENT(IN)     :: v
    REAL(rp), INTENT(IN)     :: ne
    REAL(rp), INTENT(IN)     :: Te
    REAL(rp),DIMENSION(cparams_ms%num_impurity_species), INTENT(IN)     :: nimp
    REAL(rp)                 :: CF_SD_FIO
    REAL(rp)                 :: CF_temp
    REAL(rp)                 :: x
    INTEGER :: i
    REAL(rp)  :: k=5._rp
    x = v/VTe(Te)
    CF_SD_FIO  = Gammacee(v,ne,Te)*psi(x)/Te
    if (params%bound_electron_model.eq.'HESSLOW') then
       CF_temp=CF_SD_FIO
       do i=1,cparams_ms%num_impurity_species
          CF_temp=CF_temp+CF_SD_FIO*nimp(i)/ne* &
               (cparams_ms%Zo(i)-cparams_ms%Zj(i))/ &
               CLogee(v,ne,Te)*(log(1+h_j(i,v)**k)/k-v**2)
       end do
       CF_SD_FIO=CF_temp
    end if
  end function CF_SD_FIO
Call graph
cf_sd_fio calls psi, vte, gammacee, clogee, h_j
gammacee calls clogee
clogee calls vte, clog0
include_coulombcollisionsla_gc_p calls cf_sd_fio
include_coulombcollisions_gcfio_p calls cf_sd_fio
include_coulombcollisions_gc_p calls cf_sd_fio
advance_fpeqn_vars calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, advance_fpinterp_vars
advance_gcinterp_fio_vars calls include_coulombcollisions_gcfio_p
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
adv_gceqn_top calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
main calls adv_gcinterp_psi_top, adv_gcinterp_psiwe_top, adv_gceqn_top, adv_gcinterp_psi_top_fs, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_gcinterp_3dbdb_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_b2d_top
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars