CF_SD – KORC
CF_SD Function
33 statements
Source File
private function CF_SD(params, v, ne, Te)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
real(kind=rp), intent(in) :: v
real(kind=rp), intent(in) :: ne
real(kind=rp), intent(in) :: Te
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
CF_SD
Source Code
  function CF_SD(params,v,ne,Te)
    TYPE(KORC_PARAMS), INTENT(IN)     :: params
    REAL(rp), INTENT(IN)     :: v
    REAL(rp), INTENT(IN)     :: ne
    REAL(rp), INTENT(IN)     :: Te
    REAL(rp)                 :: CF_SD
    REAL(rp)                 :: CF_temp
    REAL(rp)                 :: x
    INTEGER :: i
    REAL(rp)  :: k=5._rp
    x = v/VTe(Te)
    CF_SD  = Gammacee(v,ne,Te)*psi(x)/Te
    if (params%bound_electron_model.eq.'HESSLOW') then
       CF_temp=CF_SD
       if ((cparams_ms%Zj(1).eq.0.0).and. &
            (neut_prof.eq.'UNIFORM')) then
          CF_temp=CF_temp+CF_SD*cparams_ms%nz(1)/ne* &
               (cparams_ms%Zo(1)-cparams_ms%Zj(1))/ &
               CLogee(v,ne,Te)*(log(1+h_j(1,v)**k)/k-v**2)
       else if ((cparams_ms%Zj(1).eq.0.0).and. &
            (neut_prof.eq.'HOLLOW')) then
          CF_temp=CF_temp+CF_SD*max(cparams_ms%nz(1)-ne,0._rp)/ne* &
               (cparams_ms%Zo(1)-cparams_ms%Zj(1))/ &
               CLogee(v,ne,Te)*(log(1+h_j(1,v)**k)/k-v**2)
       else
          CF_temp=CF_temp+CF_SD*cparams_ms%nz(1)/cparams_ms%ne* &
               (cparams_ms%Zo(1)-cparams_ms%Zj(1))/ &
               CLogee(v,ne,Te)*(log(1+h_j(1,v)**k)/k-v**2)
       endif
       do i=2,cparams_ms%num_impurity_species
          CF_temp=CF_temp+CF_SD*cparams_ms%nz(i)/cparams_ms%ne* &
               (cparams_ms%Zo(i)-cparams_ms%Zj(i))/ &
               CLogee(v,ne,Te)*(log(1+h_j(i,v)**k)/k-v**2)
       end do
       CF_SD=CF_temp
    else if (params%bound_electron_model.eq.'ROSENBLUTH') then
       CF_temp=CF_SD
       do i=1,cparams_ms%num_impurity_species
          CF_temp=CF_temp+CF_SD*cparams_ms%nz(i)/cparams_ms%ne* &
               (cparams_ms%Zo(i)-cparams_ms%Zj(i))/2._rp
       end do
       CF_SD=CF_temp
    end if
  end function CF_SD
Call graph
cf_sd calls psi, vte, gammacee, clogee, h_j
gammacee calls clogee
clogee calls vte, clog0
include_coulombcollisionsla_gc_p calls cf_sd
include_coulombcollisions_gc_p calls cf_sd
include_coulombcollisions_fo_p calls cf_sd
include_coulombcollisions_fofio_p calls cf_sd
advance_fpeqn_vars calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, advance_fpinterp_vars
advance_foeqn_vars calls include_coulombcollisions_fo_p
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_fofio_vars calls include_coulombcollisions_fofio_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
adv_gceqn_top calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_fointerp_top calls advance_fp3dinterp_vars, advance_fointerp_vars
adv_fofio_top calls advance_fp3dinterp_vars, advance_fofio_vars
adv_fointerp_mars_top calls advance_fointerp_vars
main calls adv_gcinterp_psi_top, adv_gcinterp_psiwe_top, adv_gceqn_top, adv_gcinterp_psi_top_fs, adv_fointerp_top, adv_fofio_top, adv_fointerp_mars_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_foeqn_top, adv_fointerp_aorsa_top, adv_gcinterp_3dbdb_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_b2d_top
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_foeqn_top calls advance_foeqn_vars, advance_fp3deqn_vars
adv_fointerp_aorsa_top calls advance_fointerp_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars