check_if_in_profiles_domain_p – KORC
check_if_in_profiles_domain_p Subroutine
28 statements
Source File
private subroutine check_if_in_profiles_domain_p(pchunk, Y_R, Y_PHI, Y_Z, flag)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: pchunk
real(kind=rp), intent(in), DIMENSION(pchunk) :: Y_R
real(kind=rp), intent(in), DIMENSION(pchunk) :: Y_PHI
real(kind=rp), intent(in), DIMENSION(pchunk) :: Y_Z
integer(kind=is), intent(inout), DIMENSION(pchunk) :: flag
Flag that determines whether particles are followed in the simulation (flag=1), or not (flag=0).
Called by
Contents
Source Code
check_if_in_profiles_domain_p
Source Code
  subroutine check_if_in_profiles_domain_p(pchunk,Y_R,Y_PHI,Y_Z,flag)
    INTEGER, INTENT(IN)  :: pchunk
    REAL(rp), DIMENSION(pchunk),  INTENT(IN)      :: Y_R,Y_PHI,Y_Z
    INTEGER(is), DIMENSION(pchunk), INTENT(INOUT)  :: flag
    !! Flag that determines whether particles are followed
    !! in the simulation (flag=1), or not (flag=0).
    INTEGER                                                :: IR
    !! @param IR Variable used to localize the grid cell in
    !! the \((R,\phi,Z)\) or \((R,Z)\) grid containing the fields data that
    !! corresponds to the radial position of the particles.
    INTEGER                                                :: IPHI
    !! @param IPHI Variable used to localize the grid cell in
    !! the \((R,\phi,Z)\) or \((R,Z)\) grid containing the fields data that
    !! corresponds to the azimuthal position of the particles.
    INTEGER                                                :: IZ
    !! @param IZ Variable used to localize the grid cell in the
    !! \((R,\phi,Z)\) or \((R,Z)\) grid containing the fields data that
    !! corresponds to the vertical position of the particles.
    INTEGER(ip)                                            :: pp
    !! @param pp Particle iterator.
    INTEGER(ip)                                            :: ss
    !! @param ss Species iterator.
    if (ALLOCATED(profiles_domain%FLAG3D)) then
       !$OMP SIMD
!       !$OMP& aligned(IR,IPHI,IZ)
       do pp=1_idef,pchunk
          IR = INT(FLOOR((Y_R(pp)  - profiles_domain%Ro + &
               0.5_rp*profiles_domain%DR)/profiles_domain%DR) + 1.0_rp,idef)
          IPHI = INT(FLOOR((Y_PHI(pp)  + 0.5_rp*profiles_domain%DPHI)/ &
               profiles_domain%DPHI) + 1.0_rp,idef)
          IZ = INT(FLOOR((Y_Z(pp)  + ABS(profiles_domain%Zo) + &
               0.5_rp*profiles_domain%DZ)/profiles_domain%DZ) + 1.0_rp,idef)
          if ((profiles_domain%FLAG3D(IR,IPHI,IZ).NE.1_is).OR. &
               ((IR.GT.profiles_3d%NR).OR.(IZ.GT.profiles_3d%NZ))) then
             flag(pp) = 0_is
          end if
       end do
       !$OMP END SIMD
    else
       !$OMP SIMD
!       !$OMP& aligned(IR,IZ)
       do pp=1_idef,pchunk
          IR = INT(FLOOR((Y_R(pp)  - profiles_domain%Ro + &
               0.5_rp*profiles_domain%DR)/profiles_domain%DR) + 1.0_rp,idef)
          IZ = INT(FLOOR((Y_Z(pp)  + ABS(profiles_domain%Zo) + &
               0.5_rp*profiles_domain%DZ)/profiles_domain%DZ) + 1.0_rp,idef)
          if ((profiles_domain%FLAG2D(IR,IZ).NE.1_is).OR. &
               ((IR.GT.profiles_2d%NR).OR.(IZ.GT.profiles_2d%NZ))) then
             flag(pp) = 0_is
!             write(output_unit_write,'("Shit''s fucked.")')
          end if
       end do
       !$OMP END SIMD
!       write(output_unit_write,'("Shit''s not fucked.")')
    end if
  end subroutine check_if_in_profiles_domain_p
Call graph
interp_collision_p calls check_if_in_profiles_domain_p
interp_focollision_p calls check_if_in_profiles_domain_p
interp_nre calls check_if_in_profiles_domain_p
interp_hcollision_p calls check_if_in_profiles_domain_p
gceom1_p calls interp_focollision_p
include_coulombcollisions_gc_p calls interp_focollision_p, interp_hcollision_p
include_coulombcollisions_fo_p calls interp_focollision_p
include_coulombcollisionsla_gc_p calls interp_focollision_p, interp_hcollision_p
sample_hollmann_distribution_1dtransport calls interp_nre
advance_gcinterp_psiwe_vars calls gceom1_p
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, advance_fpinterp_vars
advance_gcinterp_3dbdb1_vars calls gceom1_p, include_coulombcollisions_gc_p
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_gcinterp_psi_vars calls gceom1_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_psi2x1t_vars calls gceom1_p, include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls gceom1_p, include_coulombcollisions_gc_p
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_2dbdb_vars calls gceom1_p, include_coulombcollisions_gc_p
get_hollmann_distribution_1dtransport calls sample_hollmann_distribution_1dtransport
adv_gceqn_top calls include_coulombcollisions_gc_p
advance_gcinterp_b_vars calls gceom1_p, include_coulombcollisions_gc_p
advance_fpeqn_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psi_vars_fs calls gceom1_p, include_coulombcollisions_gc_p
advance_gcinterp_b2d_vars calls gceom1_p, include_coulombcollisions_gc_p
advance_foeqn_vars calls include_coulombcollisions_fo_p
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_fointerp_top calls advance_fp3dinterp_vars, advance_fointerp_vars
adv_fofio_top calls advance_fp3dinterp_vars
adv_fointerp_mars_top calls advance_fointerp_vars
main calls adv_gcinterp_psi_top, adv_gceqn_top, adv_gcinterp_psiwe_top, adv_gcinterp_psi_top_fs, adv_fointerp_top, adv_fofio_top, adv_fointerp_mars_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_foeqn_top, adv_gcinterp_3dbdb_top, adv_fointerp_aorsa_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_b2d_top
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_foeqn_top calls advance_fp3deqn_vars, advance_foeqn_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_fointerp_aorsa_top calls advance_fointerp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars