CLogee – KORC
CLogee Function
18 statements
Source File
public function CLogee(v, ne, Te)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: v
real(kind=rp), intent(in) :: ne
ne is in m^-3 and below is converted to cm^-3
real(kind=rp), intent(in) :: Te
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
CLogee
Source Code
  function CLogee(v,ne,Te)
    REAL(rp), INTENT(IN)     :: v
    REAL(rp), INTENT(IN)     :: ne
    !! ne is in m^-3 and below is converted to cm^-3
    REAL(rp), INTENT(IN)     :: Te ! In Joules
    REAL(rp)                 :: CLogee
    REAL(rp)  :: k=5._rp
    REAL(rp)  :: gam
    REAL(rp) :: gam_min
    gam=1/sqrt(1-v**2)
    gam_min=cparams_ss%gam_min
    if (cparams_ss%Clog_model.eq.'HESSLOW') then
       CLogee = CLog0(ne,Te)+ &
            log(1+(2*(gam-1)/VTe(Te)**2)**(k/2._rp))/k
    else if (cparams_ss%Clog_model.eq.'CONSTANT') then
       CLogee = cparams_ss%Clog_const
    else if (cparams_ss%Clog_model.eq.'MCDEVITT') then
       CLogee = CLog0(ne,Te)+ &
            log(1+(2*(gam-1)/VTe(Te)**2)**(k/2._rp))/k+ &
            log(sqrt(2*(gam_min-1._rp)/(gam-1._rp)))
    end if
!    write(output_unit_write,*) gam,CLogee
  end function CLogee
Call graph
clogee calls clog0, vte
cf_fio calls clogee
cf_sd_fio calls clogee, gammacee
cf calls clogee
gammacee calls clogee
cf_sd calls clogee, gammacee
cb_ei_sd calls clogee, gammacee
cb_ei_sd_fio calls clogee, gammacee
cb_ei_fio calls clogee
cb_ei calls clogee
ca_sd calls gammacee
nu_s_fio calls cf_fio
dca_sd calls gammacee
include_coulombcollisions_gc_p calls cf_sd_fio, cf_sd, cb_ei_sd, cb_ei_sd_fio, ca_sd, dca_sd, cb_ee_sd
large_angle_source calls gammacee
include_coulombcollisions_fo_p calls cf_sd, cb_ei_sd, ca_sd, dca_sd, cb_ee_sd
include_coulombcollisionsla_gc_p calls cf_sd_fio, cf_sd, cb_ei_sd, cb_ei_sd_fio, ca_sd, dca_sd, large_angle_source, cb_ee_sd
include_coulombcollisions_gcfio_p calls cf_sd_fio, cb_ei_sd_fio, ca_sd, dca_sd, cb_ee_sd
nu_d_fio calls cb_ei_fio
nu_s calls cf
include_coulombcollisions_fofio_p calls cf_sd, cb_ei_sd, ca_sd, dca_sd, cb_ee_sd
cb_ee_sd calls gammacee
nu_d calls cb_ei
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, advance_fpinterp_vars
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
define_collisions_time_step calls nu_s_fio, nu_d_fio, nu_s, nu_d
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
adv_gceqn_top calls include_coulombcollisions_gc_p
advance_fofio_vars calls include_coulombcollisions_fofio_p
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
advance_fpeqn_vars calls include_coulombcollisions_gc_p
advance_gcinterp_fio_vars calls include_coulombcollisions_gcfio_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_foeqn_vars calls include_coulombcollisions_fo_p
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_fointerp_top calls advance_fp3dinterp_vars, advance_fointerp_vars
adv_fofio_top calls advance_fp3dinterp_vars, advance_fofio_vars
adv_fointerp_mars_top calls advance_fointerp_vars
main calls adv_gcinterp_psi_top, define_collisions_time_step, adv_gceqn_top, adv_gcinterp_psiwe_top, adv_gcinterp_psi_top_fs, adv_fointerp_top, adv_fofio_top, adv_fointerp_mars_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_foeqn_top, adv_gcinterp_3dbdb_top, adv_fointerp_aorsa_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_b2d_top
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_foeqn_top calls advance_fp3deqn_vars, advance_foeqn_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_fointerp_aorsa_top calls advance_fointerp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars