CLog0 – KORC
CLog0 Function
6 statements
Source File
public function CLog0(ne, Te)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: ne
real(kind=rp), intent(in) :: Te
Return Value real(kind=rp)
Called by
Contents
Source Code
CLog0
Source Code
  function CLog0(ne,Te) ! Dimensionless ne and Te
    REAL(rp), INTENT(IN)     :: ne
    REAL(rp), INTENT(IN)     :: Te
    REAL(rp)                 :: CLog0
    CLog0 = 14.9_rp - LOG(ne)/2._rp + LOG(Te) + &
         cparams_ss%CLog0_1 + cparams_ss%CLog0_2
  end function CLog0
Call graph
clogei calls clog0
clogee calls clog0
cf_fio calls clogee
cf_sd_fio calls clogee, gammacee
cf calls clogee
gammacee calls clogee
cb_ei_sd calls clogei, clogee, gammacee
cf_sd calls clogee, gammacee
cb_ei_sd_fio calls clogei, clogee, gammacee
cb_ei_fio calls clogei, clogee
cb_ei calls clogei, clogee
ca_sd calls gammacee
nu_s_fio calls cf_fio
dca_sd calls gammacee
include_coulombcollisions_gc_p calls cf_sd_fio, cb_ei_sd, cf_sd, cb_ei_sd_fio, ca_sd, dca_sd, cb_ee_sd
large_angle_source calls gammacee
include_coulombcollisions_fo_p calls cb_ei_sd, cf_sd, ca_sd, dca_sd, cb_ee_sd
include_coulombcollisionsla_gc_p calls cf_sd_fio, cb_ei_sd, cf_sd, cb_ei_sd_fio, ca_sd, dca_sd, large_angle_source, cb_ee_sd
include_coulombcollisions_gcfio_p calls cf_sd_fio, cb_ei_sd_fio, ca_sd, dca_sd, cb_ee_sd
nu_d_fio calls cb_ei_fio
nu_s calls cf
include_coulombcollisions_fofio_p calls cb_ei_sd, cf_sd, ca_sd, dca_sd, cb_ee_sd
cb_ee_sd calls gammacee
nu_d calls cb_ei
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, advance_fpinterp_vars
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
define_collisions_time_step calls nu_s_fio, nu_d_fio, nu_s, nu_d
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
adv_gceqn_top calls include_coulombcollisions_gc_p
advance_fofio_vars calls include_coulombcollisions_fofio_p
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
advance_fpeqn_vars calls include_coulombcollisions_gc_p
advance_gcinterp_fio_vars calls include_coulombcollisions_gcfio_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_foeqn_vars calls include_coulombcollisions_fo_p
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_fointerp_top calls advance_fp3dinterp_vars, advance_fointerp_vars
adv_fofio_top calls advance_fp3dinterp_vars, advance_fofio_vars
adv_fointerp_mars_top calls advance_fointerp_vars
main calls adv_gcinterp_psi_top, define_collisions_time_step, adv_gceqn_top, adv_gcinterp_psiwe_top, adv_gcinterp_psi_top_fs, adv_fointerp_top, adv_fofio_top, adv_fointerp_mars_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_foeqn_top, adv_gcinterp_3dbdb_top, adv_fointerp_aorsa_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_b2d_top
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_foeqn_top calls advance_fp3deqn_vars, advance_foeqn_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_fointerp_aorsa_top calls advance_fointerp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars