CLogei – KORC
CLogei Function
15 statements
Source File
public function CLogei(v, ne, Te)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: v
real(kind=rp), intent(in) :: ne
ne is in m^-3 and below is converted to cm^-3
real(kind=rp), intent(in) :: Te
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
CLogei
Source Code
  function CLogei(v,ne,Te)
    REAL(rp), INTENT(IN)     :: v
    REAL(rp), INTENT(IN)     :: ne
    !! ne is in m^-3 and below is converted to cm^-3
    REAL(rp), INTENT(IN)     :: Te ! In Joules
    REAL(rp)                 :: CLogei
    REAL(rp)  :: k=5._rp
    REAL(rp)  :: gam,p
    gam=1/sqrt(1-v**2)
    p=gam*v
    if (cparams_ss%Clog_model.eq.'CONSTANT') then
       CLogei = cparams_ss%Clog_const
    else
       CLogei = CLog0(ne,Te)+log(1+(2*p/VTe(Te))**k)/k
    end if
  end function CLogei
Call graph
clogei calls clog0, vte
cb_ei_sd_fio calls clogei
cb_ei_fio calls clogei
cb_ei_sd calls clogei
cb_ei calls clogei
include_coulombcollisions_gc_p calls cb_ei_sd_fio, cb_ei_sd
include_coulombcollisions_fo_p calls cb_ei_sd
include_coulombcollisionsla_gc_p calls cb_ei_sd_fio, cb_ei_sd
include_coulombcollisions_gcfio_p calls cb_ei_sd_fio
nu_d_fio calls cb_ei_fio
include_coulombcollisions_fofio_p calls cb_ei_sd
nu_d calls cb_ei
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, advance_fpinterp_vars
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
define_collisions_time_step calls nu_d_fio, nu_d
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
adv_gceqn_top calls include_coulombcollisions_gc_p
advance_fofio_vars calls include_coulombcollisions_fofio_p
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
advance_fpeqn_vars calls include_coulombcollisions_gc_p
advance_gcinterp_fio_vars calls include_coulombcollisions_gcfio_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_foeqn_vars calls include_coulombcollisions_fo_p
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_fointerp_top calls advance_fp3dinterp_vars, advance_fointerp_vars
adv_fofio_top calls advance_fp3dinterp_vars, advance_fofio_vars
adv_fointerp_mars_top calls advance_fointerp_vars
main calls adv_gcinterp_psi_top, define_collisions_time_step, adv_gceqn_top, adv_gcinterp_psiwe_top, adv_gcinterp_psi_top_fs, adv_fointerp_top, adv_fofio_top, adv_fointerp_mars_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_foeqn_top, adv_gcinterp_3dbdb_top, adv_fointerp_aorsa_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_b2d_top
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_foeqn_top calls advance_fp3deqn_vars, advance_foeqn_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_fointerp_aorsa_top calls advance_fointerp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars