CLog0_wu – KORC
CLog0_wu Function
6 statements
Source File
public function CLog0_wu(ne, Te)
With units
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: ne
ne is in m^-3 and below is converted to cm^-3
real(kind=rp), intent(in) :: Te
Return Value real(kind=rp)
Called by
Contents
Source Code
CLog0_wu
Source Code
  function CLog0_wu(ne,Te)
    !! With units
    REAL(rp), INTENT(IN)     :: ne
    !! ne is in m^-3 and below is converted to cm^-3
    REAL(rp), INTENT(IN)     :: Te ! In Joules
    REAL(rp)                 :: CLog0_wu
    CLog0_wu = 14.9_rp - LOG(1E-20_rp*ne)/2._rp + LOG(1E-3_rp*Te/C_E)
  end function CLog0_wu
Call graph
clogee_wu calls clog0_wu
clogei_wu calls clog0_wu
load_params_ss calls clogee_wu, clogei_wu, gammac_wu
gammac_wu calls clogee_wu
initialize_collision_params calls load_params_ss, load_params_ms
load_params_ms calls gammac_wu
main calls initialize_collision_params