CLogee_wu – KORC
CLogee_wu Function
14 statements
Source File
public function CLogee_wu(params, ne, Te)
With units
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
real(kind=rp), intent(in) :: ne
ne is in m^-3 and below is converted to cm^-3
real(kind=rp), intent(in) :: Te
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
CLogee_wu
Source Code
  function CLogee_wu(params,ne,Te)
    !! With units
    TYPE(KORC_PARAMS), INTENT(IN)     :: params
    REAL(rp), INTENT(IN)     :: ne
    !! ne is in m^-3 and below is converted to cm^-3
    REAL(rp), INTENT(IN)     :: Te ! In Joules
    REAL(rp)                 :: CLogee_wu
    REAL(rp)  :: k=5._rp
    if (cparams_ss%Clog_model.eq.'HESSLOW') then
       CLogee_wu = CLog0_wu(ne,Te)+ &
            log(1+(2*(params%minimum_particle_g-1)/ &
            (VTe_wu(Te)/C_C)**2)**(k/2._rp))/k
    else if (cparams_ss%Clog_model.eq.'CONSTANT') then
       CLogee_wu = cparams_ss%Clog_const
    else if (cparams_ss%Clog_model.eq.'MCDEVITT') then
       CLogee_wu = CLog0_wu(ne,Te)+ &
            log(1+(2*(params%minimum_particle_g-1)/ &
            (VTe_wu(Te)/C_C)**2)**(k/2._rp))/k
    end if
  end function CLogee_wu
Call graph
clogee_wu calls clog0_wu, vte_wu
load_params_ss calls clogee_wu, gammac_wu
gammac_wu calls clogee_wu
initialize_collision_params calls load_params_ss, load_params_ms
load_params_ms calls gammac_wu
main calls initialize_collision_params