deg2rad – KORC
deg2rad Function
5 statements
Source File
private function deg2rad(x)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: x
Return Value real(kind=rp)
Called by
Contents
Source Code
deg2rad
Source Code
  FUNCTION deg2rad(x)
    REAL(rp), INTENT(IN) :: x
    REAL(rp) :: deg2rad
    deg2rad = C_PI*x/180.0_rp
  END FUNCTION deg2rad
Call graph
fre_h_pitch calls deg2rad
sample_hollmann_distribution_3d calls deg2rad, fre_h_3d
sample_hollmann_distribution_3d_psi calls deg2rad, fre_h_3d
fre_h calls deg2rad
sample_hollmann_distribution calls deg2rad, fre_h
pr calls deg2rad
sample_hollmann_distribution_1dtransport calls deg2rad, fre_h_pitch
fre_h_3d calls deg2rad
fre calls deg2rad
get_hollmann_distribution_3d calls sample_hollmann_distribution_3d
sample_distribution calls fre
fre_hxpr calls fre_h, pr
frexpr calls pr, fre
get_hollmann_distribution_1dtransport calls sample_hollmann_distribution_1dtransport
get_hollmann_distribution_3d_psi calls sample_hollmann_distribution_3d_psi
get_hollmann_distribution calls sample_hollmann_distribution
get_experimentalg_distribution calls sample_distribution