fGamma – KORC
fGamma Function
7 statements
Source File
private function fGamma(x, k, t)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: x
real(kind=rp), intent(in) :: k
real(kind=rp), intent(in) :: t
Return Value real(kind=rp)
Called by
Contents
Source Code
fGamma
Source Code
  FUNCTION fGamma(x,k,t)
    REAL(rp), INTENT(IN) :: x ! Independent variable
    REAL(rp), INTENT(IN) :: k ! Shape factor
    REAL(rp), INTENT(IN) :: t ! Scale factor
    REAL(rp) :: fGamma
    fGamma = x**(k - 1.0_rp)*EXP(-x/t)/(GAMMA(k)*t**k)
  END FUNCTION fGamma
Call graph
intgamma calls fgamma
fre calls fgamma
frexpr calls fre
sample_distribution calls fre
initialize_params calls intgamma
get_experimentalg_distribution calls sample_distribution, initialize_params