fRE – KORC
fRE Function
7 statements
Source File
private function fRE(p)
Evaluation of the energy distribution function @f$f_{RE}(\mathcal{E})@f$ of runaway electrons as function of the normalized momentum @f$p' = p/m_ec@f$. Here, @f$p'@f$ is the normalized momentum and @f$m_e@f$ and @f$c@f$ are the electron mass and the speed of light.
@param p Normalized momentum @f$p' = p/m_ec@f$ of a given electron in the simulation. @param fRE Computed value of the energy distribution function of runaway electrons. @param Eo Normalized energy @f$\mathcal{E}' = \sqrt{1 + p'}@f$ of the the electron with normalized momentum @f$p'@f$.
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: p
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
fRE
Source Code
  FUNCTION fRE(p)
    REAL(rp), INTENT(IN)     :: p ! momentum in units of mc
    REAL(rp)                 :: fRE
    REAL(rp)                 :: Eo ! In units of mc^2
    Eo = SQRT(p**2.0_rp + 1.0_rp)
    fRE = fGamma(Eo,gamma_pdf_params%k,gamma_pdf_params%t*co)
  END FUNCTION fRE
Call graph
fre calls fgamma
sample_gamma_distribution calls fre
get_gamma_distribution calls sample_gamma_distribution