fRE_HxPR – KORC
fRE_HxPR Function
6 statements
Source File
public function fRE_HxPR(eta, g)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: eta
real(kind=rp), intent(in) :: g
Return Value real(kind=rp)
Calls
Contents
Source Code
fRE_HxPR
Source Code
  FUNCTION fRE_HxPR(eta,g)
    REAL(rp), INTENT(IN) :: eta ! pitch angle in degrees
    REAL(rp), INTENT(IN) :: g ! gamma factor
    REAL(rp) :: fRE_HxPR
    fRE_HxPR = fRE_H(eta,g)*PR(eta,SQRT(g**2 - 1.0_rp),h_params%Bo,h_params%lambda)
  END FUNCTION fRE_HxPR
Call graph
fre_hxpr calls pr, fre_h
pr calls p_integral, deg2rad
fre_h calls deg2rad
p_integral calls intbesselk, intk
intbesselk calls besselk