fRExPR – KORC
fRExPR Function
8 statements
Source File
private function fRExPR(eta, p)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: eta
real(kind=rp), intent(in) :: p
Return Value real(kind=rp)
Calls
Contents
Source Code
fRExPR
Source Code
  FUNCTION fRExPR(eta,p)
    REAL(rp), INTENT(IN) :: eta ! pitch angle in degrees
    REAL(rp), INTENT(IN) :: p ! momentum in units of mc
    REAL(rp) :: fRExPR
    REAL(rp) :: A
    REAL(rp) :: Eo
    fRExPR = fRE(eta,p)*PR(eta,p,pdf_params%Bo,pdf_params%lambda)
  END FUNCTION fRExPR
Call graph
frexpr calls pr, fre
pr calls p_integral, deg2rad
fre calls fgamma, deg2rad
p_integral calls intbesselk, intk
intbesselk calls besselk