fRE – KORC
fRE Function
15 statements
Source File
private function fRE(eta, p)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: eta
real(kind=rp), intent(in) :: p
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
fRE
Source Code
  FUNCTION fRE(eta,p)
    REAL(rp), INTENT(IN)     :: eta ! pitch angle in degrees
    REAL(rp), INTENT(IN)     :: p ! momentum in units of mc
    REAL(rp)                 :: fRE
    REAL(rp)                 :: fE
    REAL(rp)                 :: feta
    REAL(rp)                 :: A
    REAL(rp)                 :: Eo
    Eo = SQRT(p**2.0_rp + 1.0_rp)
    A = (2.0_rp*pdf_params%E/(pdf_params%Zeff + 1.0_rp))*(p**2/SQRT(p**2.0_rp + 1.0_rp))
    A = A*pdf_params%A_fact
    feta = 0.5_rp*A*EXP(A*COS(deg2rad(eta)))/SINH(A)
    fE = fGamma(Eo,pdf_params%k,pdf_params%t/xo)/pdf_params%fGo
    fRE = fE*feta
  END FUNCTION fRE
Call graph
fre calls fgamma, deg2rad
frexpr calls fre
sample_distribution calls fre
get_experimentalg_distribution calls sample_distribution