Gammacee – KORC
Gammacee Function
7 statements
Source File
private function Gammacee(v, ne, Te)
Dimensionless ne and Te
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: v
real(kind=rp), intent(in) :: ne
real(kind=rp), intent(in) :: Te
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
Gammacee
Source Code
  function Gammacee(v,ne,Te)
    !! Dimensionless ne and Te
    REAL(rp), INTENT(IN)     :: v
    REAL(rp), INTENT(IN)     :: ne
    REAL(rp), INTENT(IN)     :: Te
    REAL(rp)                 :: Gammacee
    Gammacee = ne*CLogee(v,ne,Te)*cparams_ss%Gammaco
  end function Gammacee
Call graph
gammacee calls clogee
clogee calls clog0, vte
cf_sd_fio calls gammacee
ca_sd calls gammacee
dca_sd calls gammacee
large_angle_source calls gammacee
cf_sd calls gammacee
cb_ei_sd calls gammacee
cb_ei_sd_fio calls gammacee
cb_ee_sd calls gammacee
include_coulombcollisions_gc_p calls cf_sd_fio, ca_sd, dca_sd, cf_sd, cb_ei_sd, cb_ei_sd_fio, cb_ee_sd
include_coulombcollisions_fo_p calls ca_sd, dca_sd, cf_sd, cb_ei_sd, cb_ee_sd
include_coulombcollisionsla_gc_p calls cf_sd_fio, ca_sd, dca_sd, large_angle_source, cf_sd, cb_ei_sd, cb_ei_sd_fio, cb_ee_sd
include_coulombcollisions_gcfio_p calls cf_sd_fio, ca_sd, dca_sd, cb_ei_sd_fio, cb_ee_sd
include_coulombcollisions_fofio_p calls ca_sd, dca_sd, cf_sd, cb_ei_sd, cb_ee_sd
advance_fpeqn_vars calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, advance_fpinterp_vars
advance_foeqn_vars calls include_coulombcollisions_fo_p
advance_gcinterp_fio_vars calls include_coulombcollisions_gcfio_p
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_fofio_vars calls include_coulombcollisions_fofio_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
adv_gceqn_top calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_fointerp_top calls advance_fp3dinterp_vars, advance_fointerp_vars
adv_fofio_top calls advance_fp3dinterp_vars, advance_fofio_vars
adv_fointerp_mars_top calls advance_fointerp_vars
main calls adv_gcinterp_psi_top, adv_gcinterp_psiwe_top, adv_gceqn_top, adv_gcinterp_psi_top_fs, adv_fointerp_top, adv_fofio_top, adv_fointerp_mars_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_foeqn_top, adv_fointerp_aorsa_top, adv_gcinterp_3dbdb_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_b2d_top
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_foeqn_top calls advance_foeqn_vars, advance_fp3deqn_vars
adv_fointerp_aorsa_top calls advance_fointerp_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars