get_Hollmann_distribution_1Dtransport – KORC
get_Hollmann_distribution_1Dtransport Subroutine
16 statements
Source File
public subroutine get_Hollmann_distribution_1Dtransport(params, spp, F)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(inout) :: params
type(SPECIES), intent(inout) :: spp
type(FIELDS), intent(in) :: F
Calls
Contents
Source Code
get_Hollmann_distribution_1Dtransport
Source Code
  SUBROUTINE get_Hollmann_distribution_1Dtransport(params,spp,F)
    TYPE(FIELDS), INTENT(IN)                                   :: F
    TYPE(KORC_PARAMS), INTENT(INOUT) :: params
    TYPE(SPECIES),  INTENT(INOUT) :: spp
    INTEGER                 :: mpierr
    if (spp%ppp*params%mpi_params%nmpi.lt.10) then
       if(params%mpi_params%rank.eq.0) then
          write(6,*) 'num_samples need to be atleast 10 but is only: ', &
               spp%ppp*params%mpi_params%nmpi
       end if
       call korc_abort(12)
    end if
    call initialize_Hollmann_params(params)
    call save_Hollmann_params(params)
    call normalize_Hollmann_params(params)
#ifdef PSPLINE
    call sample_Hollmann_distribution_1Dtransport(params,spp,F)
#endif
  END SUBROUTINE get_Hollmann_distribution_1Dtransport
Call graph
get_hollmann_distribution_1dtransport calls save_hollmann_params, initialize_hollmann_params, normalize_hollmann_params, korc_abort, sample_hollmann_distribution_1dtransport
save_hollmann_params calls h5fclose_f, save_to_hdf5, h5gclose_f
initialize_hollmann_params calls load_data_from_hdf5, initialize_hollmann_interpolant
korc_abort calls mpi_abort
sample_hollmann_distribution_1dtransport calls get_random_u, fre_h_pitch, deg2rad, mpi_barrier, indicator_exp, init_random_seed, mpi_scatter, interp_nre, get_random_n
get_random_u calls random_get_number_u
fre_h_pitch calls deg2rad
save_to_hdf5 calls i2save_to_hdf5, i1save_to_hdf5, i4save_to_hdf5, i8save_to_hdf5, rsave_to_hdf5
interp_nre calls ezspline_error, ezspline_interp, check_if_in_profiles_domain_p
get_random_n calls random_get_number_n
load_data_from_hdf5 calls korc_abort, h5fclose_f, load_array_from_hdf5, h5fopen_f, load_from_hdf5
initialize_hollmann_interpolant calls ezspline_error, ezspline_init, ezspline_setup
i2save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i1save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i4save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
load_array_from_hdf5 calls rload_1d_array_from_hdf5, rload_2d_array_from_hdf5, rload_3d_array_from_hdf5
i8save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
rsave_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5dwrite_f, h5sclose_f, h5acreate_f
load_from_hdf5 calls iload_from_hdf5, rload_from_hdf5
iload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_1d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_2d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_3d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f