get_Hollmann_distribution_3D_psi – KORC
get_Hollmann_distribution_3D_psi Subroutine
16 statements
Source File
public subroutine get_Hollmann_distribution_3D_psi(params, spp, F)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(inout) :: params
type(SPECIES), intent(inout) :: spp
type(FIELDS), intent(in) :: F
Calls
Contents
Source Code
get_Hollmann_distribution_3D_psi
Source Code
  SUBROUTINE get_Hollmann_distribution_3D_psi(params,spp,F)
    TYPE(FIELDS), INTENT(IN)                                   :: F
    TYPE(KORC_PARAMS), INTENT(INOUT) :: params
    TYPE(SPECIES),  INTENT(INOUT) :: spp
    INTEGER                 :: mpierr
    if (spp%ppp*params%mpi_params%nmpi.lt.10) then
       if(params%mpi_params%rank.eq.0) then
          write(6,*) 'num_samples need to be atleast 10 but is only: ', &
               spp%ppp*params%mpi_params%nmpi
       end if
       call korc_abort(12)
    end if
    call initialize_Hollmann_params(params)
    call save_Hollmann_params(params)
    call normalize_Hollmann_params(params)
    call sample_Hollmann_distribution_3D_psi(params,spp,F)
  END SUBROUTINE get_Hollmann_distribution_3D_psi
Call graph
get_hollmann_distribution_3d_psi calls save_hollmann_params, initialize_hollmann_params, sample_hollmann_distribution_3d_psi, normalize_hollmann_params, korc_abort
save_hollmann_params calls h5fclose_f, save_to_hdf5, h5gclose_f
initialize_hollmann_params calls load_data_from_hdf5, initialize_hollmann_interpolant
sample_hollmann_distribution_3d_psi calls get_random_u, deg2rad, mpi_barrier, indicator_exp, get_fields, init_random_seed, mpi_scatter, get_random_n, fre_h_3d
korc_abort calls mpi_abort
get_random_u calls random_get_number_u
get_fields calls get_analytical_fields, interp_fields, uniform_fields
save_to_hdf5 calls i2save_to_hdf5, i1save_to_hdf5, i4save_to_hdf5, i8save_to_hdf5, rsave_to_hdf5
get_random_n calls random_get_number_n
fre_h_3d calls deg2rad
load_data_from_hdf5 calls korc_abort, h5fclose_f, load_array_from_hdf5, load_from_hdf5, h5fopen_f
initialize_hollmann_interpolant calls ezspline_error, ezspline_init, ezspline_setup
i2save_to_hdf5 calls h5screate_simple_f, h5dclose_f, h5tcopy_f, h5awrite_f, h5tset_size_f, h5aclose_f, h5sclose_f, h5acreate_f
get_analytical_fields calls cyl_check_if_confined, analytical_fields, cart_to_tor_check_if_confined, cart_to_cyl, analytical_fields_gc, analytical_fields_gc_init
i1save_to_hdf5 calls h5screate_simple_f, h5dclose_f, h5tcopy_f, h5awrite_f, h5tset_size_f, h5aclose_f, h5sclose_f, h5acreate_f
i4save_to_hdf5 calls h5screate_simple_f, h5dclose_f, h5tcopy_f, h5awrite_f, h5tset_size_f, h5aclose_f, h5sclose_f, h5acreate_f
load_array_from_hdf5 calls rload_1d_array_from_hdf5, rload_3d_array_from_hdf5, rload_2d_array_from_hdf5
i8save_to_hdf5 calls h5screate_simple_f, h5dclose_f, h5tcopy_f, h5awrite_f, h5tset_size_f, h5aclose_f, h5sclose_f, h5acreate_f
interp_fields calls korc_abort, interp_3d_bfields, get_fio_vector_potential, gradient_2d_bfields, interp_3d_efields, interp_fofields_aorsa, interp_2d_efields, interp_fofields_mars, interp_2d_curlbfields, calculate_magnetic_field, get_fio_magnetic_fields, interp_2d_gradbfields, check_if_in_lcfs, interp_2d_bfields, get_fio_electric_fields, check_if_in_fields_domain
rsave_to_hdf5 calls h5screate_simple_f, h5dclose_f, h5tcopy_f, h5dwrite_f, h5awrite_f, h5tset_size_f, h5aclose_f, h5sclose_f, h5acreate_f
load_from_hdf5 calls rload_from_hdf5, iload_from_hdf5
uniform_fields calls uniform_magnetic_field, uniform_electric_field
interp_3d_bfields calls ezspline_error
rload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_1d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
get_fio_vector_potential calls fio_eval_field
gradient_2d_bfields calls ezspline_error
rload_3d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
interp_3d_efields calls ezspline_error
interp_fofields_aorsa calls ezspline_error, ezspline_interp
interp_2d_efields calls ezspline_error
interp_fofields_mars calls ezspline_error, ezspline_interp
interp_2d_curlbfields calls ezspline_error
calculate_magnetic_field calls ezspline_error
get_fio_magnetic_fields calls omp_get_thread_num, fio_eval_field
interp_2d_gradbfields calls ezspline_error
iload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
interp_2d_bfields calls ezspline_error
get_fio_electric_fields calls fio_eval_field
rload_2d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f