get_Avalanche_4D – KORC
get_Avalanche_4D Subroutine
9 statements
Source File
public subroutine get_Avalanche_4D(params, spp, P, F)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
type(SPECIES), intent(inout) :: spp
type(PROFILES), intent(in) :: P
type(FIELDS), intent(in) :: F
An instance of the KORC derived type FIELDS.
Calls
Contents
Source Code
get_Avalanche_4D
Source Code
  SUBROUTINE get_Avalanche_4D(params,spp,P,F)
    TYPE(KORC_PARAMS), INTENT(IN) :: params
    TYPE(SPECIES), INTENT(INOUT)  :: spp
    TYPE(PROFILES), INTENT(IN)    :: P
    TYPE(FIELDS), INTENT(IN)                                   :: F
    !! An instance of the KORC derived type FIELDS.
    call initialize_avalanche_params(params)
    call save_avalanche_params(params)
    call Avalanche_4D(params,spp,P,F)
  END SUBROUTINE get_Avalanche_4D
Call graph
get_avalanche_4d calls initialize_avalanche_params, save_avalanche_params, avalanche_4d
save_avalanche_params calls h5fclose_f, save_to_hdf5, h5gclose_f
avalanche_4d calls indicator, update_avalanche_params, mpi_barrier, fre, get_profiles, mpi_scatter, random_norm, deg2rad, psi_rot
get_profiles calls cart_to_cyl, get_analytical_profiles, uniform_profiles, cart_to_tor_check_if_confined, interp_profiles, cyl_to_cart
save_to_hdf5 calls i2save_to_hdf5, i1save_to_hdf5, i4save_to_hdf5, i8save_to_hdf5, rsave_to_hdf5
i2save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i1save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i4save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i8save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
rsave_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5dwrite_f, h5sclose_f, h5acreate_f
interp_profiles calls check_if_in_profiles_domain, interp_3d_profiles, interp_2d_profiles, korc_abort, get_fio_profile
interp_3d_profiles calls ezspline_error
interp_2d_profiles calls ezspline_error
korc_abort calls mpi_abort
get_fio_profile calls fio_eval_field