get_Hollmann_distribution – KORC
get_Hollmann_distribution Subroutine
14 statements
Source File
public subroutine get_Hollmann_distribution(params, spp)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
type(SPECIES), intent(inout) :: spp
Calls
Contents
Source Code
get_Hollmann_distribution
Source Code
  SUBROUTINE get_Hollmann_distribution(params,spp)
    TYPE(KORC_PARAMS), INTENT(IN) :: params
    TYPE(SPECIES),  INTENT(INOUT) :: spp
!    REAL(rp), DIMENSION(:), ALLOCATABLE, INTENT(INOUT) :: g
!    REAL(rp), DIMENSION(:), ALLOCATABLE, INTENT(INOUT) :: eta
!    REAL(rp), INTENT(OUT) :: go
    !    REAL(rp), INTENT(OUT) :: etao
    INTEGER                 :: mpierr
    if (spp%ppp*params%mpi_params%nmpi.lt.10) then
       if(params%mpi_params%rank.eq.0) then
          write(6,*) 'num_samples need to be atleast 10 but is only: ', &
               spp%ppp*params%mpi_params%nmpi
       end if
       call korc_abort(12)
    end if
    call initialize_Hollmann_params(params)
    call save_Hollmann_params(params)
    call sample_Hollmann_distribution(params,spp)
  END SUBROUTINE get_Hollmann_distribution
Call graph
get_hollmann_distribution calls korc_abort, sample_hollmann_distribution, save_hollmann_params, initialize_hollmann_params
korc_abort calls mpi_abort
sample_hollmann_distribution calls random_norm, mpi_barrier, deg2rad, init_random_seed, fre_h, mpi_scatter
save_hollmann_params calls h5fclose_f, save_to_hdf5, h5gclose_f
initialize_hollmann_params calls load_data_from_hdf5, initialize_hollmann_interpolant
fre_h calls deg2rad
save_to_hdf5 calls i2save_to_hdf5, i1save_to_hdf5, i4save_to_hdf5, i8save_to_hdf5, rsave_to_hdf5
load_data_from_hdf5 calls korc_abort, h5fclose_f, load_array_from_hdf5, h5fopen_f, load_from_hdf5
initialize_hollmann_interpolant calls ezspline_error, ezspline_init, ezspline_setup
i2save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i1save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i4save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
load_array_from_hdf5 calls rload_1d_array_from_hdf5, rload_2d_array_from_hdf5, rload_3d_array_from_hdf5
i8save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
rsave_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5dwrite_f, h5sclose_f, h5acreate_f
load_from_hdf5 calls iload_from_hdf5, rload_from_hdf5
iload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_1d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_2d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_3d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f