get_gamma_distribution – KORC
get_gamma_distribution Subroutine
8 statements
Source File
public subroutine get_gamma_distribution(params, g, go)
@brief Subroutine that contains calls to subroutine to generate a gamma distribution for the energy distribution of a given species in the simulation.
@param[in] params Core KORC simulation parameters. @param[in,out] g Relativistic gamma factor @f$\gamma@f$ of the particles in a given species in the simulation. These are so that, they follow a Gamma distribution in energy. The parameters of the Gamma distributions are given by the user. @param[out] go Mean value of @f$\gamma@f$ of the particles in a given species. used to calculate the minimum required time step to resolve in detail the full-orbit dynamics of the particles.
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
real(kind=rp), intent(inout), DIMENSION(:), ALLOCATABLE :: g
real(kind=rp), intent(out) :: go
Calls
Contents
Source Code
get_gamma_distribution
Source Code
  SUBROUTINE get_gamma_distribution(params,g,go)
    TYPE(KORC_PARAMS), INTENT(IN)                         :: params
    REAL(rp), DIMENSION(:), ALLOCATABLE, INTENT(INOUT)     :: g
    REAL(rp), INTENT(OUT)                                 :: go
    call initialize_gamma_params(params)
    call save_gamma_params(params)
    call sample_gamma_distribution(params,g,go)
  END SUBROUTINE get_gamma_distribution
Call graph
get_gamma_distribution calls initialize_gamma_params, save_gamma_params, sample_gamma_distribution
save_gamma_params calls h5fclose_f, save_to_hdf5, h5gclose_f
sample_gamma_distribution calls mpi_bcast, mpi_barrier, random_norm, fre, mpi_scatter
save_to_hdf5 calls i2save_to_hdf5, i1save_to_hdf5, i4save_to_hdf5, i8save_to_hdf5, rsave_to_hdf5
fre calls fgamma
i2save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i1save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i4save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i8save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
rsave_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5dwrite_f, h5sclose_f, h5acreate_f