get_Hollmann_distribution_3D – KORC
get_Hollmann_distribution_3D Subroutine
16 statements
Source File
public subroutine get_Hollmann_distribution_3D(params, spp, F)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
type(SPECIES), intent(inout) :: spp
type(FIELDS), intent(in) :: F
Calls
Contents
Source Code
get_Hollmann_distribution_3D
Source Code
  SUBROUTINE get_Hollmann_distribution_3D(params,spp,F)
    TYPE(FIELDS), INTENT(IN)                                   :: F
    TYPE(KORC_PARAMS), INTENT(IN) :: params
    TYPE(SPECIES),  INTENT(INOUT) :: spp
    INTEGER                 :: mpierr
    if (spp%ppp*params%mpi_params%nmpi.lt.10) then
       if(params%mpi_params%rank.eq.0) then
          write(6,*) 'num_samples need to be atleast 10 but is only: ', &
               spp%ppp*params%mpi_params%nmpi
       end if
       call korc_abort(12)
    end if
    call initialize_Hollmann_params(params)
    call save_Hollmann_params(params)
    call normalize_Hollmann_params(params)
    call sample_Hollmann_distribution_3D(params,spp,F)
  END SUBROUTINE get_Hollmann_distribution_3D
Call graph
get_hollmann_distribution_3d calls save_hollmann_params, sample_hollmann_distribution_3d, initialize_hollmann_params, normalize_hollmann_params, korc_abort
save_hollmann_params calls h5fclose_f, save_to_hdf5, h5gclose_f
sample_hollmann_distribution_3d calls get_random_u, deg2rad, mpi_barrier, indicator_exp, init_random_seed, mpi_scatter, get_random_n, fre_h_3d, psi_rot_exp
initialize_hollmann_params calls initialize_hollmann_interpolant, load_data_from_hdf5
korc_abort calls mpi_abort
get_random_u calls random_get_number_u
initialize_hollmann_interpolant calls ezspline_error, ezspline_init, ezspline_setup
save_to_hdf5 calls i2save_to_hdf5, i1save_to_hdf5, i4save_to_hdf5, i8save_to_hdf5, rsave_to_hdf5
get_random_n calls random_get_number_n
fre_h_3d calls deg2rad
load_data_from_hdf5 calls korc_abort, h5fclose_f, load_array_from_hdf5, h5fopen_f, load_from_hdf5
i2save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i1save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i4save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
load_array_from_hdf5 calls rload_1d_array_from_hdf5, rload_2d_array_from_hdf5, rload_3d_array_from_hdf5
i8save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
rsave_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5dwrite_f, h5sclose_f, h5acreate_f
load_from_hdf5 calls iload_from_hdf5, rload_from_hdf5
iload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_1d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_2d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_3d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f