get_randoms – KORC
get_randoms Subroutine
9 statements
Source File
public subroutine get_randoms(nums)
Uses
omp_lib
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(out), DIMENSION(:) :: nums
Calls
Called by
Contents
Source Code
get_randoms
Source Code
  SUBROUTINE get_randoms(nums)
    USE omp_lib
    IMPLICIT NONE
    REAL(rp), DIMENSION(:), INTENT(OUT) :: nums
    INTEGER                             :: i
    !$OMP PARALLEL DO DEFAULT(SHARED) PRIVATE(i)
    DO i = 1, SIZE(nums)
       nums(i) = get_random()
    END DO
    !$OMP END PARALLEL DO
  END SUBROUTINE get_randoms
Call graph
get_randoms calls get_random
get_random calls omp_get_thread_num, random_get_number
torus calls get_randoms