get_random – KORC
get_random Function
6 statements
Source File
public function get_random()
Uses
omp_lib
Arguments
None
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
get_random
Source Code
  FUNCTION get_random()
    USE omp_lib
    IMPLICIT NONE
    REAL(rp)            :: get_random
    get_random = random_get_number(states(OMP_GET_THREAD_NUM()))
  END FUNCTION get_random
Call graph
get_random calls omp_get_thread_num, random_get_number
large_angle_source calls get_random
include_coulombcollisions_gc_p calls get_random
check_collisions_params calls get_random
include_coulombcollisions_fo_p calls get_random
include_coulombcollisionsla_gc_p calls get_random, large_angle_source
include_coulombcollisions_gcfio_p calls get_random
include_coulombcollisions_fofio_p calls get_random
get_randoms calls get_random
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, advance_fpinterp_vars
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
adv_gceqn_top calls include_coulombcollisions_gc_p
torus calls get_randoms
advance_fofio_vars calls include_coulombcollisions_fofio_p
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
advance_fpeqn_vars calls include_coulombcollisions_gc_p
advance_gcinterp_fio_vars calls include_coulombcollisions_gcfio_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_foeqn_vars calls include_coulombcollisions_fo_p
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_fointerp_top calls advance_fp3dinterp_vars, advance_fointerp_vars
adv_fofio_top calls advance_fp3dinterp_vars, advance_fofio_vars
adv_fointerp_mars_top calls advance_fointerp_vars
main calls adv_gcinterp_psi_top, adv_gceqn_top, adv_gcinterp_psiwe_top, adv_gcinterp_psi_top_fs, adv_fointerp_top, adv_fofio_top, adv_fointerp_mars_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_foeqn_top, adv_gcinterp_3dbdb_top, adv_fointerp_aorsa_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_b2d_top
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_foeqn_top calls advance_fp3deqn_vars, advance_foeqn_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_fointerp_aorsa_top calls advance_fointerp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars