h_j – KORC
h_j Function
10 statements
Source File
public function h_j(i, v)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
real(kind=rp), intent(in) :: v
Return Value real(kind=rp)
Called by
Contents
Source Code
h_j
Source Code
  function h_j(i,v)
    INTEGER, INTENT(IN)     :: i
    REAL(rp), INTENT(IN)     :: v
    REAL(rp)  :: gam
    REAL(rp)  :: p
    REAL(rp)  :: h_j
    gam=1/sqrt(1-v**2)
    p=v*gam
    h_j=p*sqrt(gam-1)/cparams_ms%IZj(i)
  end function h_j
Call graph
cf_fio calls h_j
cf_sd calls h_j
cf calls h_j
cf_sd_fio calls h_j
nu_s_fio calls cf_fio
include_coulombcollisions_gc_p calls cf_sd, cf_sd_fio
include_coulombcollisions_fo_p calls cf_sd
include_coulombcollisionsla_gc_p calls cf_sd, cf_sd_fio
include_coulombcollisions_gcfio_p calls cf_sd_fio
nu_s calls cf
include_coulombcollisions_fofio_p calls cf_sd
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, advance_fpinterp_vars
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
define_collisions_time_step calls nu_s_fio, nu_s
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
adv_gceqn_top calls include_coulombcollisions_gc_p
advance_fofio_vars calls include_coulombcollisions_fofio_p
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
advance_fpeqn_vars calls include_coulombcollisions_gc_p
advance_gcinterp_fio_vars calls include_coulombcollisions_gcfio_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_foeqn_vars calls include_coulombcollisions_fo_p
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_fointerp_top calls advance_fp3dinterp_vars, advance_fointerp_vars
adv_fofio_top calls advance_fp3dinterp_vars, advance_fofio_vars
adv_fointerp_mars_top calls advance_fointerp_vars
main calls adv_gcinterp_psi_top, define_collisions_time_step, adv_gceqn_top, adv_gcinterp_psiwe_top, adv_gcinterp_psi_top_fs, adv_fointerp_top, adv_fofio_top, adv_fointerp_mars_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_foeqn_top, adv_gcinterp_3dbdb_top, adv_fointerp_aorsa_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_b2d_top
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_foeqn_top calls advance_fp3deqn_vars, advance_foeqn_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_fointerp_aorsa_top calls advance_fointerp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars