indicator_exp – KORC
indicator_exp Function
10 statements
Source File
public function indicator_exp(psi, psi_max)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: psi
real(kind=rp), intent(in) :: psi_max
Return Value real(kind=rp)
Called by
Contents
Source Code
indicator_exp
Source Code
FUNCTION indicator_exp(psi,psi_max)
  REAL(rp), INTENT(IN)  :: psi
  REAL(rp), INTENT(IN)  :: psi_max
  REAL(rp)              :: indicator_exp
  IF (psi.LT.psi_max) THEN
     indicator_exp=1
  ELSE
     indicator_exp=0
  END IF
END FUNCTION indicator_exp
Call graph
sample_hollmann_distribution_1dtransport calls indicator_exp
sample_hollmann_distribution_3d calls indicator_exp
sample_hollmann_distribution_3d_psi calls indicator_exp
get_hollmann_distribution_3d calls sample_hollmann_distribution_3d
get_hollmann_distribution_1dtransport calls sample_hollmann_distribution_1dtransport
get_hollmann_distribution_3d_psi calls sample_hollmann_distribution_3d_psi