indicator – KORC
indicator Function
10 statements
Source File
private function indicator(psi, psi_max)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: psi
real(kind=rp), intent(in) :: psi_max
Return Value real(kind=rp)
Called by
Contents
Source Code
indicator
Source Code
FUNCTION indicator(psi,psi_max)
  REAL(rp), INTENT(IN)  :: psi
  REAL(rp), INTENT(IN)  :: psi_max
  REAL(rp)              :: indicator
  IF (psi.LT.psi_max) THEN
     indicator=1
  ELSE
     indicator=0
  END IF
END FUNCTION indicator
Call graph
fio_therm calls indicator
spong_3d calls indicator
mh_psi calls indicator
mh_gaussian_elliptic_torus calls indicator
bmc_radial calls indicator