initialize_HDF5 – KORC
initialize_HDF5 Subroutine
7 statements
Source File
public subroutine initialize_HDF5()
Arguments
None
Calls
Called by
Contents
Source Code
initialize_HDF5
Source Code
  subroutine initialize_HDF5()
    INTEGER :: h5error  ! Error flag
    call h5open_f(h5error)
#ifdef HDF5_DOUBLE_PRESICION
    call h5tcopy_f(H5T_NATIVE_DOUBLE, KORC_HDF5_REAL, h5error)
#elif HDF5_SINGLE_PRESICION
    call h5tcopy_f(H5T_NATIVE_REAL, KORC_HDF5_REAL, h5error)
#endif
    call h5tget_size_f(KORC_HDF5_REAL, rp_hdf5, h5error)
  end subroutine initialize_HDF5
Call graph
initialize_hdf5 calls h5open_f, h5tget_size_f, h5tcopy_f
main calls initialize_hdf5