interp_FOcollision_p – KORC
interp_FOcollision_p Subroutine
9 statements
Source File
public subroutine interp_FOcollision_p(pchunk, Y_R, Y_PHI, Y_Z, ne, Te, Zeff, flag_cache)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: pchunk
real(kind=rp), intent(in), DIMENSION(pchunk) :: Y_R
real(kind=rp), intent(in), DIMENSION(pchunk) :: Y_PHI
real(kind=rp), intent(in), DIMENSION(pchunk) :: Y_Z
real(kind=rp), intent(out), DIMENSION(pchunk) :: ne
real(kind=rp), intent(out), DIMENSION(pchunk) :: Te
real(kind=rp), intent(out), DIMENSION(pchunk) :: Zeff
integer(kind=is), intent(inout), DIMENSION(pchunk) :: flag_cache
Calls
Called by
Contents
Source Code
interp_FOcollision_p
Source Code
subroutine interp_FOcollision_p(pchunk,Y_R,Y_PHI,Y_Z,ne,Te,Zeff,flag_cache)
  INTEGER, INTENT(IN)  :: pchunk
  REAL(rp),DIMENSION(pchunk),INTENT(IN)   :: Y_R,Y_PHI,Y_Z
  REAL(rp),DIMENSION(pchunk),INTENT(OUT)   :: ne,Te,Zeff
  INTEGER(is),DIMENSION(pchunk),INTENT(INOUT)   :: flag_cache
  call check_if_in_profiles_domain_p(pchunk,Y_R,Y_PHI,Y_Z,flag_cache)
!  write(output_unit_write,'("YR: ",E17.10)') Y_R(1)
!  write(output_unit_write,'("YPHI: ",E17.10)') Y_PHI(1)
!  write(output_unit_write,'("YZ: ",E17.10)') Y_Z(1)
!  write(output_unit_write,'("Te_interp_R",E17.10)') profiles_2d%Te%x1
!  write(output_unit_write,'("Te_interp_Z",E17.10)') profiles_2d%Te%x2
  call EZspline_interp(profiles_2d%ne,profiles_2d%Te, &
       profiles_2d%Zeff,pchunk,Y_R,Y_Z,ne,Te,Zeff,ezerr)
  ! this will call PSPLINE routine EZspline_interp2_bmag_cloud as there
  ! is the same number of entries
  call EZspline_error(ezerr)
end subroutine interp_FOcollision_p
Call graph
interp_focollision_p calls ezspline_interp, check_if_in_profiles_domain_p, ezspline_error
include_coulombcollisionsla_gc_p calls interp_focollision_p
gceom1_p calls interp_focollision_p
include_coulombcollisions_gc_p calls interp_focollision_p
include_coulombcollisions_fo_p calls interp_focollision_p
advance_fpeqn_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psiwe_vars calls gceom1_p
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, advance_fpinterp_vars
advance_foeqn_vars calls include_coulombcollisions_fo_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb1_vars calls gceom1_p, include_coulombcollisions_gc_p
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_psi_vars_fs calls gceom1_p, include_coulombcollisions_gc_p
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_gcinterp_psi_vars calls gceom1_p
advance_gcinterp_b2d_vars calls gceom1_p, include_coulombcollisions_gc_p
advance_gcinterp_psi2x1t_vars calls gceom1_p, include_coulombcollisions_gc_p
advance_gcinterp_2dbdb_vars calls gceom1_p, include_coulombcollisions_gc_p
advance_gcinterp_b_vars calls gceom1_p, include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls gceom1_p, include_coulombcollisions_gc_p
adv_gceqn_top calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_fointerp_top calls advance_fp3dinterp_vars, advance_fointerp_vars
adv_fofio_top calls advance_fp3dinterp_vars
adv_fointerp_mars_top calls advance_fointerp_vars
main calls adv_gcinterp_psi_top, adv_gcinterp_psiwe_top, adv_gceqn_top, adv_gcinterp_psi_top_fs, adv_fointerp_top, adv_fofio_top, adv_fointerp_mars_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_foeqn_top, adv_gcinterp_3dbdb_top, adv_fointerp_aorsa_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_b2d_top
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_foeqn_top calls advance_foeqn_vars, advance_fp3deqn_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_fointerp_aorsa_top calls advance_fointerp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars