korc_abort – KORC
korc_abort Subroutine
6 statements
Source File
public subroutine korc_abort(errorcode)
Note
Subroutine that terminates the simulation.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: errorcode
Calls
Called by
Contents
Source Code
korc_abort
Source Code
  subroutine korc_abort(errorcode)
    !! @note Subroutine that terminates the simulation. @endnote
    INTEGER,INTENT(IN) :: errorcode
    INTEGER :: mpierr
    !! MPI error status
    !! 11: korc_hpc:set_paths
    !! 12: korc_experimental:get_Hollmann_distribution
    !! 13: korc_input:read_namelist
    !! 14: korc_hpc:load_particle_ic
    !! 15: korc_interp:interp_fields
    !! 16: korc_interp:interp_profiles
    !! 17: korc_fields:mean_F_field
    !! 18: korc_fields:initialize_fields
    !! 19: korc_spatial_distribution:initial_spatial_distribution
    !! 20: korc_experimental_pdf:load_data_from_hdf5
    !! 21: korc_interp:get_fio_ion_p
    !! 22: korc_fio_interface:initialize_nimrod
    !! 23: korc_interp:check_if_in_fields_domain
    !! 24: korc_collisions:large_angle_source
    !! 25: korc_ppusher:adv_GCinterp_psiwE_top
    !! 26: korc_collisions:define_collisions_time_step
    flush(output_unit_write)
    !call MPI_BARRIER(MPI_COMM_WORLD,mpierr)
    call MPI_ABORT(MPI_COMM_WORLD, errorcode, mpierr)
  end subroutine korc_abort
Call graph
korc_abort calls mpi_abort
get_hollmann_distribution_3d calls korc_abort, initialize_hollmann_params
rload_from_hdf5 calls korc_abort
rload_1d_array_from_hdf5 calls korc_abort
rload_3d_array_from_hdf5 calls korc_abort
get_hollmann_distribution calls korc_abort, initialize_hollmann_params
load_data_from_hdf5 calls korc_abort, load_array_from_hdf5, load_from_hdf5
load_data_from_hdf5_bmc calls korc_abort, load_array_from_hdf5, load_from_hdf5
read_namelist calls korc_abort
set_paths calls korc_abort
get_hollmann_distribution_1dtransport calls korc_abort, initialize_hollmann_params
load_time_stepping_params calls korc_abort, load_from_hdf5
load_prev_iter calls korc_abort, load_from_hdf5
intitial_spatial_distribution calls korc_abort
interp_fields calls korc_abort
interp_profiles calls korc_abort
load_particles_ic calls korc_abort, load_array_from_hdf5
initialize_fields calls korc_abort, load_prev_iter, allocate_1d_fs_arrays, load_1d_fs_from_hdf5, load_field_data_from_hdf5, load_dim_data_from_hdf5
iload_from_hdf5 calls korc_abort
load_prev_time calls korc_abort, load_from_hdf5
mean_f_field calls korc_abort
rload_2d_array_from_hdf5 calls korc_abort
get_hollmann_distribution_3d_psi calls korc_abort, initialize_hollmann_params, sample_hollmann_distribution_3d_psi
adv_gcinterp_psiwe_top calls korc_abort
initialize_m3d_c1 calls load_prev_iter
main calls initialize_fields, adv_gcinterp_psiwe_top, initialize_m3d_c1, initialize_korc_parameters, initialize_nimrod, set_up_particles_ic, define_time_step, initialize_communications, initialize_profiles
get_profiles calls interp_profiles
initialize_korc_parameters calls read_namelist
initialize_hollmann_params calls load_data_from_hdf5
initialize_nimrod calls load_prev_iter
load_array_from_hdf5 calls rload_1d_array_from_hdf5, rload_3d_array_from_hdf5, rload_2d_array_from_hdf5
get_fields calls interp_fields
initialize_mpi calls set_paths
set_up_particles_ic calls intitial_spatial_distribution, load_particles_ic
bmc_radial calls load_data_from_hdf5_bmc
define_time_step calls load_time_stepping_params, load_prev_time
load_from_hdf5 calls rload_from_hdf5, iload_from_hdf5
avalanche_4d calls get_profiles
load_profiles_data_from_hdf5 calls load_array_from_hdf5, load_from_hdf5
allocate_1d_fs_arrays calls load_from_hdf5
load_1d_fs_from_hdf5 calls load_array_from_hdf5
sample_hollmann_distribution_3d_psi calls get_fields
load_field_data_from_hdf5 calls load_array_from_hdf5, load_from_hdf5
mh_psi calls get_fields
load_dim_data_from_hdf5 calls load_from_hdf5
initialize_communications calls initialize_mpi
unitvectors calls get_fields
get_avalanche_4d calls avalanche_4d
gyro_distribution calls unitvectors
initialize_profiles calls load_profiles_data_from_hdf5