load_data_from_hdf5_BMC – KORC
load_data_from_hdf5_BMC Subroutine
33 statements
Source File
public subroutine load_data_from_hdf5_BMC(params, Nr_a, r_a, nRE)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
integer, intent(out) :: Nr_a
real(kind=rp), intent(out), ALLOCATABLE, DIMENSION(:) :: r_a
real(kind=rp), intent(out), ALLOCATABLE, DIMENSION(:) :: nRE
Calls
Called by
Contents
Source Code
load_data_from_hdf5_BMC
Source Code
SUBROUTINE load_data_from_hdf5_BMC(params,Nr_a,r_a,nRE)
  TYPE(KORC_PARAMS), INTENT(IN) :: params
  CHARACTER(MAX_STRING_LENGTH) :: filename
  CHARACTER(MAX_STRING_LENGTH) :: gname
  CHARACTER(MAX_STRING_LENGTH) :: subgname
  CHARACTER(MAX_STRING_LENGTH) :: dset
  INTEGER(HID_T) :: h5file_id
  INTEGER(HID_T) :: group_id
  INTEGER(HID_T) :: subgroup_id
  REAL(rp) :: rdatum
  INTEGER :: h5error
  INTEGER, intent(out) :: Nr_a
  REAL(rp), INTENT(out), ALLOCATABLE,DIMENSION(:) :: r_a,nRE
  filename = TRIM(filename_exp)
  call h5fopen_f(filename, H5F_ACC_RDONLY_F, h5file_id, h5error)
  if (h5error .EQ. -1) then
     write(output_unit_write,'("KORC ERROR: Something went wrong in: load_data_from_hdf5 (korc_experimental) --> h5fopen_f")')
     call korc_abort(20)
  end if
  dset = "/Nr_a"
  call load_from_hdf5(h5file_id,dset,rdatum)
  Nr_a = INT(rdatum)
  ALLOCATE(r_a(Nr_a))
  ALLOCATE(nRE(Nr_a))
  dset = "/r_a"
  call load_array_from_hdf5(h5file_id,dset,r_a)
  dset = "/nRE"
  call load_array_from_hdf5(h5file_id,dset,nRE)
  call h5fclose_f(h5file_id, h5error)
  if (h5error .EQ. -1) then
     write(output_unit_write,'("KORC ERROR: Something went wrong in: load_data_from_hdf5 (korc_experimental) --> h5fclose_f")')
  end if
END SUBROUTINE load_data_from_hdf5_BMC
Call graph
load_data_from_hdf5_bmc calls h5fclose_f, korc_abort, load_array_from_hdf5, h5fopen_f, load_from_hdf5
korc_abort calls mpi_abort
load_array_from_hdf5 calls rload_1d_array_from_hdf5, rload_2d_array_from_hdf5, rload_3d_array_from_hdf5
load_from_hdf5 calls iload_from_hdf5, rload_from_hdf5
iload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_1d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_2d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_3d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
bmc_radial calls load_data_from_hdf5_bmc