lower_triangle – KORC
lower_triangle Function
9 statements
Source File
public function lower_triangle(j, k, extra)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(in) :: j
integer(kind=I4B), intent(in) :: k
integer(kind=I4B), intent(in), optional :: extra
Return Value logical(kind=LGT), DIMENSION(j,k)
Calls
Contents
Source Code
lower_triangle
Source Code
    FUNCTION lower_triangle(j,k,extra)
    INTEGER(I4B), INTENT(IN) :: j,k
    INTEGER(I4B), OPTIONAL, INTENT(IN) :: extra
    LOGICAL(LGT), DIMENSION(j,k) :: lower_triangle
    INTEGER(I4B) :: n
    n=0
    if (present(extra)) n=extra
    lower_triangle=(outerdiff(arth_i(1,1,j),arth_i(1,1,k)) > -n)
    END FUNCTION lower_triangle
Call graph
lower_triangle calls outerdiff, arth_i
outerdiff calls outerdiff_r, outerdiff_i, outerdiff_d