nu_D – KORC
nu_D Function
8 statements
Source File
private function nu_D(params, v)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
real(kind=rp), intent(in) :: v
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
nu_D
Source Code
  function nu_D(params,v)
    ! perpendicular diffusion (pitch angle scattering) collision frequency
    REAL(rp), INTENT(IN)     :: v
    TYPE(KORC_PARAMS), INTENT(IN)     :: params
      ! Normalised particle speed
    REAL(rp)                 :: nu_D
    REAL(rp)                 :: p
    p = v/SQRT(1.0_rp - v**2)
    nu_D = 2.0_rp*(CB_ee(v)+CB_ei(params,v))/p**2
  end function nu_D
Call graph
nu_d calls cb_ee, cb_ei
cb_ee calls psi
cb_ei calls clogei, g_j, clogee
clogei calls clog0, vte
clogee calls clog0, vte
define_collisions_time_step calls nu_d
main calls define_collisions_time_step