nu_D_FIO – KORC
nu_D_FIO Function
8 statements
Source File
private function nu_D_FIO(params, v)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
real(kind=rp), intent(in) :: v
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
nu_D_FIO
Source Code
    function nu_D_FIO(params,v)
    ! perpendicular diffusion (pitch angle scattering) collision frequency
    REAL(rp), INTENT(IN)     :: v
    TYPE(KORC_PARAMS), INTENT(IN)     :: params
      ! Normalised particle speed
    REAL(rp)                 :: nu_D_FIO
    REAL(rp)                 :: p
    p = v/SQRT(1.0_rp - v**2)
    nu_D_FIO = 2.0_rp*(CB_ee(v)+CB_ei_FIO(params,v))/p**2
  end function nu_D_FIO
Call graph
nu_d_fio calls cb_ee, cb_ei_fio
cb_ee calls psi
cb_ei_fio calls clogei, g_j, clogee
clogei calls clog0, vte
clogee calls clog0, vte
define_collisions_time_step calls nu_d_fio
main calls define_collisions_time_step