psi – KORC
psi Function
5 statements
Source File
public function psi(x)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: x
Return Value real(kind=rp)
Called by
Contents
Source Code
psi
Source Code
  function psi(x)
    REAL(rp), INTENT(IN)     :: x
    REAL(rp)                 :: psi
    psi = 0.5_rp*(ERF(x) - 2.0_rp*x*EXP(-x**2)/SQRT(C_PI))/x**2
  end function psi
Call graph
ca calls psi
cf_fio calls psi
cf_sd_fio calls psi
cb_ee calls psi
ca_sd calls psi
dca_sd calls psi
cf calls psi
cf_sd calls psi
cb_ee_sd calls psi
fun calls psi
nu_s_fio calls cf_fio
include_coulombcollisions_gc_p calls cf_sd_fio, ca_sd, dca_sd, cf_sd, cb_ee_sd
include_coulombcollisions_fo_p calls ca_sd, dca_sd, cf_sd, cb_ee_sd
include_coulombcollisionsla_gc_p calls cf_sd_fio, ca_sd, dca_sd, cf_sd, cb_ee_sd
include_coulombcollisions_gcfio_p calls cf_sd_fio, ca_sd, dca_sd, cb_ee_sd
nu_d_fio calls cb_ee
nu_s calls cf
include_coulombcollisions_fofio_p calls ca_sd, dca_sd, cf_sd, cb_ee_sd
nu_par calls ca
nu_d calls cb_ee
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, advance_fpinterp_vars
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
define_collisions_time_step calls nu_s_fio, nu_d_fio, nu_s, nu_par, nu_d
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
adv_gceqn_top calls include_coulombcollisions_gc_p
advance_fofio_vars calls include_coulombcollisions_fofio_p
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
advance_fpeqn_vars calls include_coulombcollisions_gc_p
advance_gcinterp_fio_vars calls include_coulombcollisions_gcfio_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_foeqn_vars calls include_coulombcollisions_fo_p
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_fointerp_top calls advance_fp3dinterp_vars, advance_fointerp_vars
adv_fofio_top calls advance_fp3dinterp_vars, advance_fofio_vars
adv_fointerp_mars_top calls advance_fointerp_vars
main calls adv_gcinterp_psi_top, define_collisions_time_step, adv_gceqn_top, adv_gcinterp_psiwe_top, adv_gcinterp_psi_top_fs, adv_fointerp_top, adv_fofio_top, adv_fointerp_mars_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_foeqn_top, adv_gcinterp_3dbdb_top, adv_fointerp_aorsa_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_b2d_top
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_foeqn_top calls advance_fp3deqn_vars, advance_foeqn_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_fointerp_aorsa_top calls advance_fointerp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars