random_norm – KORC
random_norm Function
9 statements
Source File
private function random_norm(mean, sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: mean
real(kind=rp), intent(in) :: sigma
Return Value real(kind=rp)
Called by
Contents
Source Code
random_norm
Source Code
  FUNCTION random_norm(mean,sigma)
    REAL(rp), INTENT(IN) :: mean
    REAL(rp), INTENT(IN) :: sigma
    REAL(rp) :: random_norm
    REAL(rp) :: rand1, rand2
    call RANDOM_NUMBER(rand1)
    call RANDOM_NUMBER(rand2)
    random_norm = mean+sigma*SQRT(-2.0_rp*LOG(rand1))*COS(2.0_rp*C_PI*rand2)
  END FUNCTION random_norm
Call graph
sample_hollmann_distribution calls random_norm
sample_distribution calls random_norm
get_experimentalg_distribution calls sample_distribution
get_hollmann_distribution calls sample_hollmann_distribution