rload_3d_array_from_hdf5 – KORC
rload_3d_array_from_hdf5 Subroutine
37 statements
Source File
private subroutine rload_3d_array_from_hdf5(h5file_id, dset, rdata, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
real(kind=rp), intent(inout), DIMENSION(:,:,:), ALLOCATABLE :: rdata
character(len=MAX_STRING_LENGTH), intent(in), optional DIMENSION(:), ALLOCATABLE :: attr
Calls
Called by
Contents
Source Code
rload_3d_array_from_hdf5
Source Code
  subroutine rload_3d_array_from_hdf5(h5file_id,dset,rdata,attr)
    INTEGER(HID_T), INTENT(IN)                     :: h5file_id
    CHARACTER(MAX_STRING_LENGTH), INTENT(IN)             :: dset
    REAL(rp), DIMENSION(:,:,:), ALLOCATABLE, INTENT(INOUT)     :: rdata
    REAL, DIMENSION(:,:,:), ALLOCATABLE                 :: raw_data
    CHARACTER(MAX_STRING_LENGTH), OPTIONAL, DIMENSION(:), ALLOCATABLE, INTENT(IN)     :: attr
    CHARACTER(MAX_STRING_LENGTH)                             :: aname
    INTEGER(HID_T)                                     :: dset_id
    INTEGER(HID_T)                                     :: dspace_id
    INTEGER(HID_T)                                     :: aspace_id
    INTEGER(HID_T)                                     :: attr_id
    INTEGER(HID_T)                                     :: atype_id
    INTEGER(HSIZE_T), DIMENSION(3)                 :: dims
    INTEGER(HSIZE_T), DIMENSION(3)                 :: adims
    INTEGER                             :: h5error
    dims = shape(rdata)
    ALLOCATE( raw_data(dims(1),dims(2),dims(3)) )
    ! * * * Read data from file * * *
    call h5dopen_f(h5file_id, TRIM(dset), dset_id, h5error)
    if (h5error .EQ. -1) then
       write(output_unit_write,'("KORC ERROR: Something went wrong in: rload_from_hdf5 --> h5dopen_f")')
       call KORC_ABORT(14)
    end if
    call h5dread_f(dset_id, H5T_NATIVE_REAL, raw_data, dims, h5error)
    if (h5error .EQ. -1) then
       write(output_unit_write,'("KORC ERROR: Something went wrong in: rload_from_hdf5 --> h5dread_f")')
       call KORC_ABORT(14)
    end if
    rdata = REAL(raw_data,rp)
    call h5dclose_f(dset_id, h5error)
    if (h5error .EQ. -1) then
       write(output_unit_write,'("KORC ERROR: Something went wrong in: rload_from_hdf5 --> h5dclose_f")')
       call KORC_ABORT(14)
    end if
    DEALLOCATE( raw_data )
    if (PRESENT(attr)) then
       ! * * * Read data attribute(s) from file * * *
    end if
    ! * * * Read data from file * * *
  end subroutine rload_3d_array_from_hdf5
Call graph
rload_3d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
korc_abort calls mpi_abort
load_array_from_hdf5 calls rload_3d_array_from_hdf5
load_profiles_data_from_hdf5 calls load_array_from_hdf5
load_1d_fs_from_hdf5 calls load_array_from_hdf5
load_data_from_hdf5_bmc calls load_array_from_hdf5
load_field_data_from_hdf5 calls load_array_from_hdf5
load_particles_ic calls load_array_from_hdf5
load_data_from_hdf5 calls load_array_from_hdf5
initialize_fields calls load_1d_fs_from_hdf5, load_field_data_from_hdf5
initialize_hollmann_params calls load_data_from_hdf5
initialize_profiles calls load_profiles_data_from_hdf5
set_up_particles_ic calls load_particles_ic
bmc_radial calls load_data_from_hdf5_bmc
get_hollmann_distribution_3d calls initialize_hollmann_params
main calls initialize_fields, initialize_profiles, set_up_particles_ic
get_hollmann_distribution_1dtransport calls initialize_hollmann_params
get_hollmann_distribution_3d_psi calls initialize_hollmann_params
get_hollmann_distribution calls initialize_hollmann_params