rload_from_hdf5 – KORC
rload_from_hdf5 Subroutine
34 statements
Source File
private subroutine rload_from_hdf5(h5file_id, dset, rdatum, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
real(kind=rp), intent(out) :: rdatum
character(len=MAX_STRING_LENGTH), intent(out), optional :: attr
Calls
Called by
Contents
Source Code
rload_from_hdf5
Source Code
  subroutine rload_from_hdf5(h5file_id,dset,rdatum,attr)
    INTEGER(HID_T), INTENT(IN)                 :: h5file_id
    CHARACTER(MAX_STRING_LENGTH), INTENT(IN)         :: dset
    REAL(rp), INTENT(OUT)                 :: rdatum
    REAL                         :: raw_datum
    CHARACTER(MAX_STRING_LENGTH), OPTIONAL, INTENT(OUT) :: attr
    CHARACTER(4)                     :: aname = "Info"
    INTEGER(HID_T)                     :: dset_id
    INTEGER(HID_T)                     :: dspace_id
    INTEGER(HID_T)                     :: aspace_id
    INTEGER(HID_T)                     :: attr_id
    INTEGER(HID_T)                     :: atype_id
    INTEGER(HSIZE_T), DIMENSION(1)             :: dims = (/1/)
    INTEGER(HSIZE_T), DIMENSION(1)             :: adims = (/1/)
    INTEGER                         :: h5error
    ! * * * Read datum from file * * *
    call h5dopen_f(h5file_id, TRIM(dset), dset_id, h5error)
    if (h5error .EQ. -1) then
       write(output_unit_write,'("KORC ERROR: Something went wrong in: rload_from_hdf5 &
            --> h5dopen_f")')
       call KORC_ABORT(14)
    end if
    call h5dread_f(dset_id, H5T_NATIVE_REAL, raw_datum, dims, h5error)
    if (h5error .EQ. -1) then
       write(output_unit_write,'("KORC ERROR: Something went wrong in: rload_from_hdf5 &
            --> h5dread_f")')
       call KORC_ABORT(14)
    end if
    rdatum = REAL(raw_datum,rp)
    call h5dclose_f(dset_id, h5error)
    if (h5error .EQ. -1) then
       write(output_unit_write,'("KORC ERROR: Something went wrong in: rload_from_hdf5 &
            --> h5dclose_f")')
       call KORC_ABORT(14)
    end if
    if (PRESENT(attr)) then
       ! * * * Read attribute from file * * *
       ! * * * Read attribute from file * * *
    end if
    ! * * * Read datum from file * * *
  end subroutine rload_from_hdf5
Call graph
rload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
korc_abort calls mpi_abort
load_from_hdf5 calls rload_from_hdf5
load_time_stepping_params calls load_from_hdf5
load_profiles_data_from_hdf5 calls load_from_hdf5
allocate_1d_fs_arrays calls load_from_hdf5
load_prev_iter calls load_from_hdf5
load_prev_time calls load_from_hdf5
load_data_from_hdf5_bmc calls load_from_hdf5
load_dim_data_from_hdf5 calls load_from_hdf5
load_field_data_from_hdf5 calls load_from_hdf5
load_data_from_hdf5 calls load_from_hdf5
initialize_fields calls allocate_1d_fs_arrays, load_prev_iter, load_dim_data_from_hdf5, load_field_data_from_hdf5
initialize_m3d_c1 calls load_prev_iter
bmc_radial calls load_data_from_hdf5_bmc
initialize_hollmann_params calls load_data_from_hdf5
initialize_nimrod calls load_prev_iter
initialize_profiles calls load_profiles_data_from_hdf5
define_time_step calls load_time_stepping_params, load_prev_time
get_hollmann_distribution_3d calls initialize_hollmann_params
main calls initialize_fields, initialize_m3d_c1, initialize_nimrod, initialize_profiles, define_time_step
get_hollmann_distribution_1dtransport calls initialize_hollmann_params
get_hollmann_distribution_3d_psi calls initialize_hollmann_params
get_hollmann_distribution calls initialize_hollmann_params