rsave_to_hdf5 – KORC
rsave_to_hdf5 Subroutine
37 statements
Source File
private subroutine rsave_to_hdf5(h5file_id, dset, rdatum, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
real(kind=rp), intent(in) :: rdatum
character(len=MAX_STRING_LENGTH), intent(in), optional :: attr
Calls
Called by
Contents
Source Code
rsave_to_hdf5
Source Code
  subroutine rsave_to_hdf5(h5file_id,dset,rdatum,attr)
    INTEGER(HID_T), INTENT(IN)                             :: h5file_id
    CHARACTER(MAX_STRING_LENGTH), INTENT(IN)             :: dset
    REAL(rp), INTENT(IN)                                 :: rdatum
    CHARACTER(MAX_STRING_LENGTH), OPTIONAL, INTENT(IN)     :: attr
    CHARACTER(4)                                         :: aname = "Info"
    INTEGER(HID_T)                                         :: dset_id
    INTEGER(HID_T)                                         :: dspace_id
    INTEGER(HID_T)                                         :: aspace_id
    INTEGER(HID_T)                                         :: attr_id
    INTEGER(HID_T)                                         :: atype_id
    INTEGER(HSIZE_T), DIMENSION(1)                         :: dims = (/1/)
    INTEGER(HSIZE_T), DIMENSION(1)                         :: adims = (/1/)
    INTEGER                                             :: rank = 1
    INTEGER                                             :: arank = 1
    INTEGER(SIZE_T)                                     :: attrlen
    INTEGER                                             :: h5error
    ! * * * Write data to file * * *
    call h5screate_simple_f(rank,dims,dspace_id,h5error)
    call h5dcreate_f(h5file_id, TRIM(dset), KORC_HDF5_REAL, dspace_id, dset_id, h5error)
    if (rp .EQ. INT(rp_hdf5)) then
       call h5dwrite_f(dset_id, KORC_HDF5_REAL, rdatum, dims, h5error)
    else
       call h5dwrite_f(dset_id, KORC_HDF5_REAL, REAL(rdatum,4), dims, h5error)
    end if
    if (PRESENT(attr)) then
       ! * * * Write attribute of data to file * * *
       attrlen = LEN_TRIM(attr)
       call h5screate_simple_f(arank,adims,aspace_id,h5error)
       call h5tcopy_f(H5T_NATIVE_CHARACTER, atype_id, h5error)
       call h5tset_size_f(atype_id, attrlen, h5error)
       call h5acreate_f(dset_id, aname, atype_id, aspace_id, attr_id, h5error)
       call h5awrite_f(attr_id, atype_id, attr, adims, h5error)
       call h5aclose_f(attr_id, h5error)
       call h5sclose_f(aspace_id, h5error)
       ! * * * Write attribute of data to file * * *
    end if
    call h5sclose_f(dspace_id, h5error)
    call h5dclose_f(dset_id, h5error)
    ! * * * Write data to file * * *
  end subroutine rsave_to_hdf5
Call graph
rsave_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5dwrite_f, h5sclose_f, h5acreate_f
save_to_hdf5 calls rsave_to_hdf5
save_hollmann_params calls save_to_hdf5
save_params calls save_to_hdf5
save_gamma_params calls save_to_hdf5
save_simulation_parameters calls save_to_hdf5
save_params_ms calls save_to_hdf5
save_params_ss calls save_to_hdf5
save_restart_variables calls save_to_hdf5
save_avalanche_params calls save_to_hdf5
get_avalanche_distribution calls save_avalanche_params
get_hollmann_distribution_3d calls save_hollmann_params
get_experimentalg_distribution calls save_params
get_gamma_distribution calls save_gamma_params
save_collision_params calls save_params_ms, save_params_ss
main calls save_simulation_parameters, save_restart_variables, save_collision_params
get_equilibrium_distribution calls save_params
get_avalanche_4d calls save_avalanche_params
get_hollmann_distribution_1dtransport calls save_hollmann_params
get_hollmann_distribution_3d_psi calls save_hollmann_params
get_hollmann_distribution calls save_hollmann_params