VTe – KORC
VTe Function
5 statements
Source File
private function VTe(Te)
Dimensionless temperature
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: Te
Return Value real(kind=rp)
Called by
Contents
Source Code
VTe
Source Code
  function VTe(Te)
    !! Dimensionless temperature
    REAL(rp), INTENT(IN)     :: Te
    REAL(rp)                 :: VTe
    VTe = SQRT(2.0_rp*Te)*cparams_ss%VTeo
  end function VTe
Call graph
cf_sd_fio calls vte, clogee, gammacee
clogei calls vte
ca_sd calls vte, gammacee
dca_sd calls vte, gammacee
clogee calls vte
cf_sd calls vte, clogee, gammacee
cb_ei_sd calls vte, clogei, clogee, gammacee
delta calls vte
cb_ei_sd_fio calls vte, clogei, clogee, gammacee
cb_ee_sd calls vte, delta, gammacee
cf_fio calls clogee
include_coulombcollisions_gc_p calls cf_sd_fio, ca_sd, dca_sd, cf_sd, cb_ei_sd, cb_ei_sd_fio, cb_ee_sd
cf calls clogee
include_coulombcollisions_fo_p calls ca_sd, dca_sd, cf_sd, cb_ei_sd, cb_ee_sd
include_coulombcollisionsla_gc_p calls cf_sd_fio, ca_sd, dca_sd, cf_sd, cb_ei_sd, cb_ei_sd_fio, cb_ee_sd, large_angle_source
include_coulombcollisions_gcfio_p calls cf_sd_fio, ca_sd, dca_sd, cb_ei_sd_fio, cb_ee_sd
gammacee calls clogee
include_coulombcollisions_fofio_p calls ca_sd, dca_sd, cf_sd, cb_ei_sd, cb_ee_sd
cb_ei_fio calls clogei, clogee
cb_ei calls clogei, clogee
adv_gcinterp_psi_top calls include_coulombcollisions_gc_p, advance_fpinterp_vars
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
nu_d_fio calls cb_ei_fio
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
adv_gceqn_top calls include_coulombcollisions_gc_p
large_angle_source calls gammacee
nu_s_fio calls cf_fio
advance_fofio_vars calls include_coulombcollisions_fofio_p
nu_s calls cf
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
nu_d calls cb_ei
advance_fpeqn_vars calls include_coulombcollisions_gc_p
advance_gcinterp_fio_vars calls include_coulombcollisions_gcfio_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_foeqn_vars calls include_coulombcollisions_fo_p
adv_gcinterp_psiwe_top calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_fointerp_top calls advance_fp3dinterp_vars, advance_fointerp_vars
adv_fofio_top calls advance_fp3dinterp_vars, advance_fofio_vars
adv_fointerp_mars_top calls advance_fointerp_vars
main calls adv_gcinterp_psi_top, adv_gceqn_top, adv_gcinterp_psiwe_top, adv_gcinterp_psi_top_fs, adv_fointerp_top, adv_fofio_top, adv_fointerp_mars_top, adv_gcinterp_psi2x1t_top, define_collisions_time_step, adv_foeqn_top, adv_gcinterp_b_top, adv_gcinterp_3dbdb_top, adv_fointerp_aorsa_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_b2d_top
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
define_collisions_time_step calls nu_d_fio, nu_s_fio, nu_s, nu_d
adv_foeqn_top calls advance_fp3deqn_vars, advance_foeqn_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_fointerp_aorsa_top calls advance_fointerp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars