VTe_wu – KORC
VTe_wu Function
5 statements
Source File
private function VTe_wu(Te)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: Te
In Joules
Return Value real(kind=rp)
Called by
Contents
Source Code
VTe_wu
Source Code
  function VTe_wu(Te)
    REAL(rp), INTENT(IN)     :: Te
    !! In Joules
    REAL(rp)             :: VTe_wu
    VTe_wu = SQRT(2.0_rp*Te/C_ME)
  end function VTe_wu
Call graph
clogee_wu calls vte_wu
clogei_wu calls vte_wu
load_params_ss calls vte_wu, clogee_wu, clogei_wu, gammac_wu
initialize_collision_params calls load_params_ss, load_params_ms
gammac_wu calls clogee_wu
main calls initialize_collision_params
load_params_ms calls gammac_wu