fio_close_field – KORC
fio_close_field Interface
7 statements
Source File
interface
Called by
public function fio_close_field(ifield) bind(C, NAME='fio_close_field')
Arguments
Type Intent Optional Attributes Name
integer(kind=C_INT), intent(in), VALUE :: ifield
Return Value integer(kind=C_INT)
Call graph
initialize_nimrod calls fio_close_field
initialize_m3d_c1 calls fio_close_field
finalize_fio calls fio_close_field
initialize_m3d_c1_imp calls fio_close_field
initialize_collision_params calls initialize_m3d_c1_imp
main calls initialize_nimrod, initialize_m3d_c1, finalize_fio, initialize_m3d_c1_imp, initialize_collision_params