fio_eval_field – KORC
fio_eval_field Interface
10 statements
Source File
interface
Called by
public function fio_eval_field(ifield, x, v, hint) bind(C, NAME='fio_eval_field')
Arguments
Type Intent Optional Attributes Name
integer(kind=C_INT), intent(in), VALUE :: ifield
real(kind=C_DOUBLE), intent(in) :: x
real(kind=C_DOUBLE), intent(out) :: v
type(C_PTR), intent(in), VALUE :: hint
Return Value integer(kind=C_INT)
Call graph
initialize_m3d_c1 calls fio_eval_field
get_fio_ion_p calls fio_eval_field
get_fio_gcelectric_fields_p calls fio_eval_field
get_fio_foelectric_fields_p calls fio_eval_field
get_fio_vector_potential_p calls fio_eval_field
get_fio_magnetic_fields calls fio_eval_field
initialize_nimrod calls fio_eval_field
get_fio_fomagnetic_fields_p calls fio_eval_field
get_fio_electric_fields calls fio_eval_field
get_fio_gcmagnetic_fields_p calls fio_eval_field
get_fio_profile_p calls fio_eval_field
get_fio_vector_potential calls fio_eval_field
get_fio_profile calls fio_eval_field
adv_fofio_top calls get_fio_foelectric_fields_p, get_fio_vector_potential_p, get_fio_fomagnetic_fields_p, advance_fofio_vars
gceom1_fio_p calls get_fio_ion_p, get_fio_profile_p
advance_gcinterp_fio_vars calls get_fio_gcelectric_fields_p, get_fio_vector_potential_p, get_fio_gcmagnetic_fields_p, gceom1_fio_p, include_coulombcollisions_gcfio_p
main calls initialize_m3d_c1, initialize_nimrod, adv_fofio_top, fo_init
include_coulombcollisions_gcfio_p calls get_fio_ion_p, get_fio_gcelectric_fields_p, get_fio_vector_potential_p, get_fio_gcmagnetic_fields_p, get_fio_profile_p
interp_fields calls get_fio_magnetic_fields, get_fio_electric_fields, get_fio_vector_potential
fo_init calls get_fio_foelectric_fields_p, get_fio_vector_potential_p, get_fio_fomagnetic_fields_p
interp_profiles calls get_fio_profile
include_coulombcollisions_fofio_p calls get_fio_ion_p, get_fio_profile_p
get_profiles calls interp_profiles
advance_fofio_vars calls include_coulombcollisions_fofio_p
get_fields calls interp_fields
mh_psi calls get_fields
avalanche_4d calls get_profiles
sample_hollmann_distribution_3d_psi calls get_fields
unitvectors calls get_fields
get_avalanche_4d calls avalanche_4d
get_hollmann_distribution_3d_psi calls sample_hollmann_distribution_3d_psi
gyro_distribution calls unitvectors