geop – KORC
geop Interface
3 statements
Source File
public interface geop
Calls
Contents
Module Procedures
geop_r geop_d geop_i geop_c geop_dv
Module Procedures
public function geop_r(first, factor, n)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in) :: first
real(kind=SP), intent(in) :: factor
integer(kind=I4B), intent(in) :: n
Return Value real(kind=SP), DIMENSION(n)
public function geop_d(first, factor, n)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: first
real(kind=DP), intent(in) :: factor
integer(kind=I4B), intent(in) :: n
Return Value real(kind=DP), DIMENSION(n)
public function geop_i(first, factor, n)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(in) :: first
integer(kind=I4B), intent(in) :: factor
integer(kind=I4B), intent(in) :: n
Return Value integer(kind=I4B), DIMENSION(n)
public function geop_c(first, factor, n)
Arguments
Type Intent Optional Attributes Name
complex(kind=SP), intent(in) :: first
complex(kind=SP), intent(in) :: factor
integer(kind=I4B), intent(in) :: n
Return Value complex(kind=SP), DIMENSION(n)
public function geop_dv(first, factor, n)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in), DIMENSION(:) :: first
real(kind=DP), intent(in), DIMENSION(:) :: factor
integer(kind=I4B), intent(in) :: n
Return Value real(kind=DP), DIMENSION(size(first),n)
Call graph
geop calls geop_dv, geop_i, geop_r, geop_d, geop_c