get_diag – KORC
get_diag Interface
3 statements
Source File
public interface get_diag
Calls
Contents
Module Procedures
get_diag_rv get_diag_dv
Module Procedures
public function get_diag_rv(mat)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in), DIMENSION(:,:) :: mat
Return Value real(kind=SP), DIMENSION(size(mat,1))
public function get_diag_dv(mat)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in), DIMENSION(:,:) :: mat
Return Value real(kind=DP), DIMENSION(size(mat,1))
Call graph
get_diag calls get_diag_rv, get_diag_dv
get_diag_rv calls assert_eq2
get_diag_dv calls assert_eq2