load_from_hdf5 – KORC
load_from_hdf5 Interface
3 statements
Source File
public interface load_from_hdf5
Note
Fortran interface to subroutines loading a real or integer value from HDF5 files.
Calls
Called by
Contents
Module Procedures
iload_from_hdf5 rload_from_hdf5
Module Procedures
private subroutine iload_from_hdf5(h5file_id, dset, idatum, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
integer, intent(out) :: idatum
character(len=MAX_STRING_LENGTH), intent(out), optional :: attr
private subroutine rload_from_hdf5(h5file_id, dset, rdatum, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
real(kind=rp), intent(out) :: rdatum
character(len=MAX_STRING_LENGTH), intent(out), optional :: attr
Call graph
load_from_hdf5 calls rload_from_hdf5, iload_from_hdf5
rload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
iload_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
korc_abort calls mpi_abort
load_time_stepping_params calls load_from_hdf5
load_profiles_data_from_hdf5 calls load_from_hdf5
allocate_1d_fs_arrays calls load_from_hdf5
load_prev_iter calls load_from_hdf5
load_prev_time calls load_from_hdf5
load_data_from_hdf5_bmc calls load_from_hdf5
load_dim_data_from_hdf5 calls load_from_hdf5
load_field_data_from_hdf5 calls load_from_hdf5
load_data_from_hdf5 calls load_from_hdf5
initialize_fields calls allocate_1d_fs_arrays, load_prev_iter, load_dim_data_from_hdf5, load_field_data_from_hdf5
initialize_m3d_c1 calls load_prev_iter
bmc_radial calls load_data_from_hdf5_bmc
initialize_hollmann_params calls load_data_from_hdf5
initialize_nimrod calls load_prev_iter
initialize_profiles calls load_profiles_data_from_hdf5
define_time_step calls load_time_stepping_params, load_prev_time
get_hollmann_distribution_3d calls initialize_hollmann_params
main calls initialize_fields, initialize_m3d_c1, initialize_nimrod, initialize_profiles, define_time_step
get_hollmann_distribution_1dtransport calls initialize_hollmann_params
get_hollmann_distribution_3d_psi calls initialize_hollmann_params
get_hollmann_distribution calls initialize_hollmann_params