load_array_from_hdf5 – KORC
load_array_from_hdf5 Interface
3 statements
Source File
public interface load_array_from_hdf5
Note
Fortran interface to subroutines loading 2-D and 3-D arrays of real values from HDF5 files.
Calls
Called by
Contents
Module Procedures
rload_1d_array_from_hdf5 rload_3d_array_from_hdf5 rload_2d_array_from_hdf5
Module Procedures
private subroutine rload_1d_array_from_hdf5(h5file_id, dset, rdata, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
real(kind=rp), intent(inout), DIMENSION(:), ALLOCATABLE :: rdata
character(len=MAX_STRING_LENGTH), intent(out), optional DIMENSION(:), ALLOCATABLE :: attr
private subroutine rload_3d_array_from_hdf5(h5file_id, dset, rdata, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
real(kind=rp), intent(inout), DIMENSION(:,:,:), ALLOCATABLE :: rdata
character(len=MAX_STRING_LENGTH), intent(in), optional DIMENSION(:), ALLOCATABLE :: attr
private subroutine rload_2d_array_from_hdf5(h5file_id, dset, rdata, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
real(kind=rp), intent(inout), DIMENSION(:,:), ALLOCATABLE :: rdata
character(len=MAX_STRING_LENGTH), intent(in), optional DIMENSION(:), ALLOCATABLE :: attr
Call graph
load_array_from_hdf5 calls rload_2d_array_from_hdf5, rload_3d_array_from_hdf5, rload_1d_array_from_hdf5
rload_2d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_3d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
rload_1d_array_from_hdf5 calls korc_abort, h5dclose_f, h5dread_f
korc_abort calls mpi_abort
load_profiles_data_from_hdf5 calls load_array_from_hdf5
load_1d_fs_from_hdf5 calls load_array_from_hdf5
load_data_from_hdf5_bmc calls load_array_from_hdf5
load_field_data_from_hdf5 calls load_array_from_hdf5
load_particles_ic calls load_array_from_hdf5
load_data_from_hdf5 calls load_array_from_hdf5
initialize_fields calls load_1d_fs_from_hdf5, load_field_data_from_hdf5
initialize_hollmann_params calls load_data_from_hdf5
initialize_profiles calls load_profiles_data_from_hdf5
set_up_particles_ic calls load_particles_ic
bmc_radial calls load_data_from_hdf5_bmc
get_hollmann_distribution_3d calls initialize_hollmann_params
main calls initialize_fields, initialize_profiles, set_up_particles_ic
get_hollmann_distribution_1dtransport calls initialize_hollmann_params
get_hollmann_distribution_3d_psi calls initialize_hollmann_params
get_hollmann_distribution calls initialize_hollmann_params