poly – KORC
poly Interface
3 statements
Source File
public interface poly
Calls
Contents
Module Procedures
poly_rr poly_rrv poly_dd poly_ddv poly_rc poly_cc poly_msk_rrv poly_msk_ddv
Module Procedures
public function poly_rr(x, coeffs)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in) :: x
real(kind=SP), intent(in), DIMENSION(:) :: coeffs
Return Value real(kind=SP)
public function poly_rrv(x, coeffs)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in), DIMENSION(:) :: x
real(kind=SP), intent(in), DIMENSION(:) :: coeffs
Return Value real(kind=SP), DIMENSION(size(x))
public function poly_dd(x, coeffs)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: x
real(kind=DP), intent(in), DIMENSION(:) :: coeffs
Return Value real(kind=DP)
public function poly_ddv(x, coeffs)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in), DIMENSION(:) :: x
real(kind=DP), intent(in), DIMENSION(:) :: coeffs
Return Value real(kind=DP), DIMENSION(size(x))
public function poly_rc(x, coeffs)
Arguments
Type Intent Optional Attributes Name
complex(kind=SPC), intent(in) :: x
real(kind=SP), intent(in), DIMENSION(:) :: coeffs
Return Value complex(kind=SPC)
public function poly_cc(x, coeffs)
Arguments
Type Intent Optional Attributes Name
complex(kind=SPC), intent(in) :: x
complex(kind=SPC), intent(in), DIMENSION(:) :: coeffs
Return Value complex(kind=SPC)
public function poly_msk_rrv(x, coeffs, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in), DIMENSION(:) :: x
real(kind=SP), intent(in), DIMENSION(:) :: coeffs
logical(kind=LGT), intent(in), DIMENSION(:) :: mask
Return Value real(kind=SP), DIMENSION(size(x))
public function poly_msk_ddv(x, coeffs, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in), DIMENSION(:) :: x
real(kind=DP), intent(in), DIMENSION(:) :: coeffs
logical(kind=LGT), intent(in), DIMENSION(:) :: mask
Return Value real(kind=DP), DIMENSION(size(x))
Call graph
poly calls poly_ddv, poly_msk_ddv, poly_rr, poly_rrv, poly_dd, poly_cc, poly_msk_rrv, poly_rc
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_rrv calls poly_rr
poly_msk_rrv calls poly_rrv