random_get_number_U – KORC
random_get_number_U Interface
7 statements
Source File
interface
Called by
public function random_get_number_U(r) bind(C, NAME='random_get_number_U')
Arguments
Type Intent Optional Attributes Name
type(C_PTR), VALUE :: r
Return Value real(kind=C_DOUBLE)
Call graph
get_random_u calls random_get_number_u
sample_hollmann_distribution_3d calls get_random_u
fio_therm calls get_random_u
mh_psi calls get_random_u
sample_hollmann_distribution_3d_psi calls get_random_u
bmc_radial calls get_random_u
sample_hollmann_distribution_1dtransport calls get_random_u
get_hollmann_distribution_3d calls sample_hollmann_distribution_3d
get_hollmann_distribution_3d_psi calls sample_hollmann_distribution_3d_psi
get_hollmann_distribution_1dtransport calls sample_hollmann_distribution_1dtransport