reallocate – KORC
reallocate Interface
3 statements
Source File
public interface reallocate
Calls
Contents
Module Procedures
reallocate_rv reallocate_rm reallocate_iv reallocate_im reallocate_hv
Module Procedures
public function reallocate_rv(p, n)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), DIMENSION(:), POINTER :: p
integer(kind=I4B), intent(in) :: n
Return Value real(kind=SP), DIMENSION(:), POINTER
public function reallocate_rm(p, n, m)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), DIMENSION(:,:), POINTER :: p
integer(kind=I4B), intent(in) :: n
integer(kind=I4B), intent(in) :: m
Return Value real(kind=SP), DIMENSION(:,:), POINTER
public function reallocate_iv(p, n)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), DIMENSION(:), POINTER :: p
integer(kind=I4B), intent(in) :: n
Return Value integer(kind=I4B), DIMENSION(:), POINTER
public function reallocate_im(p, n, m)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), DIMENSION(:,:), POINTER :: p
integer(kind=I4B), intent(in) :: n
integer(kind=I4B), intent(in) :: m
Return Value integer(kind=I4B), DIMENSION(:,:), POINTER
public function reallocate_hv(p, n)
Arguments
Type Intent Optional Attributes Name
character(len=1), DIMENSION(:), POINTER :: p
integer(kind=I4B), intent(in) :: n
Return Value character(len=1), DIMENSION(:), POINTER
Call graph
reallocate calls reallocate_im, reallocate_iv, reallocate_rv, reallocate_hv, reallocate_rm