save_to_hdf5 – KORC
save_to_hdf5 Interface
3 statements
Source File
public interface save_to_hdf5
Note
Fortran interface to subroutines saving real or integer values to HDF5 files.
Calls
Called by
Contents
Module Procedures
i1save_to_hdf5 i2save_to_hdf5 i4save_to_hdf5 i8save_to_hdf5 rsave_to_hdf5
Module Procedures
private subroutine i1save_to_hdf5(h5file_id, dset, idatum, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
integer(kind=1), intent(in) :: idatum
character(len=MAX_STRING_LENGTH), intent(in), optional :: attr
private subroutine i2save_to_hdf5(h5file_id, dset, idatum, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
integer(kind=2), intent(in) :: idatum
character(len=MAX_STRING_LENGTH), intent(in), optional :: attr
private subroutine i4save_to_hdf5(h5file_id, dset, idatum, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
integer(kind=4), intent(in) :: idatum
character(len=MAX_STRING_LENGTH), intent(in), optional :: attr
private subroutine i8save_to_hdf5(h5file_id, dset, idatum, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
integer(kind=8), intent(in) :: idatum
character(len=MAX_STRING_LENGTH), intent(in), optional :: attr
private subroutine rsave_to_hdf5(h5file_id, dset, rdatum, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
real(kind=rp), intent(in) :: rdatum
character(len=MAX_STRING_LENGTH), intent(in), optional :: attr
Call graph
save_to_hdf5 calls i2save_to_hdf5, i1save_to_hdf5, i4save_to_hdf5, i8save_to_hdf5, rsave_to_hdf5
i2save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i1save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i4save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
i8save_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5sclose_f, h5acreate_f
rsave_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5dwrite_f, h5sclose_f, h5acreate_f
save_hollmann_params calls save_to_hdf5
save_params calls save_to_hdf5
save_gamma_params calls save_to_hdf5
save_simulation_parameters calls save_to_hdf5
save_params_ms calls save_to_hdf5
save_params_ss calls save_to_hdf5
save_restart_variables calls save_to_hdf5
save_avalanche_params calls save_to_hdf5
get_avalanche_distribution calls save_avalanche_params
get_hollmann_distribution_3d calls save_hollmann_params
get_experimentalg_distribution calls save_params
get_gamma_distribution calls save_gamma_params
save_collision_params calls save_params_ms, save_params_ss
main calls save_simulation_parameters, save_restart_variables, save_collision_params
get_equilibrium_distribution calls save_params
get_avalanche_4d calls save_avalanche_params
get_hollmann_distribution_1dtransport calls save_hollmann_params
get_hollmann_distribution_3d_psi calls save_hollmann_params
get_hollmann_distribution calls save_hollmann_params