save_array_to_hdf5 – KORC
save_array_to_hdf5 Interface
3 statements
Source File
public interface save_array_to_hdf5
Calls
Contents
Module Procedures
isave_1d_array_to_hdf5 rsave_1d_array_to_hdf5 rsave_2d_array_to_hdf5 rsave_3d_array_to_hdf5
Module Procedures
private subroutine isave_1d_array_to_hdf5(h5file_id, dset, idata, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
integer, intent(in), DIMENSION(:) :: idata
character(len=MAX_STRING_LENGTH), intent(in), optional DIMENSION(:), ALLOCATABLE :: attr
private subroutine rsave_1d_array_to_hdf5(h5file_id, dset, rdata, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
real(kind=rp), intent(in), DIMENSION(:) :: rdata
character(len=MAX_STRING_LENGTH), intent(in), optional DIMENSION(:), ALLOCATABLE :: attr
private subroutine rsave_2d_array_to_hdf5(h5file_id, dset, rdata, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
real(kind=rp), intent(in), DIMENSION(:,:) :: rdata
character(len=MAX_STRING_LENGTH), intent(in), optional DIMENSION(:), ALLOCATABLE :: attr
public subroutine rsave_3d_array_to_hdf5(h5file_id, dset, rdata, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
real(kind=rp), intent(in), DIMENSION(:,:,:) :: rdata
character(len=MAX_STRING_LENGTH), intent(in), optional DIMENSION(:), ALLOCATABLE :: attr
Call graph
save_array_to_hdf5 calls rsave_2d_array_to_hdf5, rsave_1d_array_to_hdf5, isave_1d_array_to_hdf5, rsave_3d_array_to_hdf5
rsave_2d_array_to_hdf5 calls h5dclose_f, h5screate_simple_f, h5dwrite_f, h5sclose_f
rsave_1d_array_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5dwrite_f, h5sclose_f, h5acreate_f
isave_1d_array_to_hdf5 calls h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5screate_simple_f, h5awrite_f, h5dwrite_f, h5sclose_f, h5acreate_f
rsave_3d_array_to_hdf5 calls h5dclose_f, h5screate_simple_f, h5dwrite_f, h5sclose_f