scatter_add – KORC
scatter_add Interface
3 statements
Source File
public interface scatter_add
Calls
Contents
Module Procedures
scatter_add_r scatter_add_d
Module Procedures
public subroutine scatter_add_r(dest, source, dest_index)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(out), DIMENSION(:) :: dest
real(kind=SP), intent(in), DIMENSION(:) :: source
integer(kind=I4B), intent(in), DIMENSION(:) :: dest_index
public subroutine scatter_add_d(dest, source, dest_index)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(out), DIMENSION(:) :: dest
real(kind=DP), intent(in), DIMENSION(:) :: source
integer(kind=I4B), intent(in), DIMENSION(:) :: dest_index
Call graph
scatter_add calls scatter_add_d, scatter_add_r
scatter_add_d calls assert_eq2
scatter_add_r calls assert_eq2