swap – KORC
swap Interface
3 statements
Source File
public interface swap
Calls
Contents
Module Procedures
swap_i swap_r swap_rv swap_c swap_cv swap_cm swap_z swap_zv swap_zm masked_swap_rs masked_swap_rv masked_swap_rm
Module Procedures
public subroutine swap_i(a, b)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(inout) :: a
integer(kind=I4B), intent(inout) :: b
public subroutine swap_r(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(inout) :: a
real(kind=SP), intent(inout) :: b
public subroutine swap_rv(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(inout), DIMENSION(:) :: a
real(kind=SP), intent(inout), DIMENSION(:) :: b
public subroutine swap_c(a, b)
Arguments
Type Intent Optional Attributes Name
complex(kind=SPC), intent(inout) :: a
complex(kind=SPC), intent(inout) :: b
public subroutine swap_cv(a, b)
Arguments
Type Intent Optional Attributes Name
complex(kind=SPC), intent(inout), DIMENSION(:) :: a
complex(kind=SPC), intent(inout), DIMENSION(:) :: b
public subroutine swap_cm(a, b)
Arguments
Type Intent Optional Attributes Name
complex(kind=SPC), intent(inout), DIMENSION(:,:) :: a
complex(kind=SPC), intent(inout), DIMENSION(:,:) :: b
public subroutine swap_z(a, b)
Arguments
Type Intent Optional Attributes Name
complex(kind=DPC), intent(inout) :: a
complex(kind=DPC), intent(inout) :: b
public subroutine swap_zv(a, b)
Arguments
Type Intent Optional Attributes Name
complex(kind=DPC), intent(inout), DIMENSION(:) :: a
complex(kind=DPC), intent(inout), DIMENSION(:) :: b
public subroutine swap_zm(a, b)
Arguments
Type Intent Optional Attributes Name
complex(kind=DPC), intent(inout), DIMENSION(:,:) :: a
complex(kind=DPC), intent(inout), DIMENSION(:,:) :: b
public subroutine masked_swap_rs(a, b, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(inout) :: a
real(kind=SP), intent(inout) :: b
logical(kind=LGT), intent(in) :: mask
public subroutine masked_swap_rv(a, b, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(inout), DIMENSION(:) :: a
real(kind=SP), intent(inout), DIMENSION(:) :: b
logical(kind=LGT), intent(in), DIMENSION(:) :: mask
public subroutine masked_swap_rm(a, b, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(inout), DIMENSION(:,:) :: a
real(kind=SP), intent(inout), DIMENSION(:,:) :: b
logical(kind=LGT), intent(in), DIMENSION(:,:) :: mask
Call graph
swap calls swap_z, swap_zv, swap_rv, swap_c, masked_swap_rs, swap_r, swap_i, swap_cm, masked_swap_rm, swap_cv, swap_zm, masked_swap_rv