u_random – KORC
u_random Interface
3 statements
Source File
public interface u_random
Calls
Contents
Module Procedures
rand_int64 rand_int32 rand_real rand_real_array
Module Procedures
private subroutine rand_int64(irand)
Arguments
Type Intent Optional Attributes Name
integer(kind=8), intent(out), optional :: irand
private subroutine rand_int32(irand32)
Arguments
Type Intent Optional Attributes Name
integer(kind=4), intent(out) :: irand32
private subroutine rand_real(rrand)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(out) :: rrand
public subroutine rand_real_array(rrand)
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(inout), DIMENSION(:) :: rrand
Call graph
u_random calls rand_int32, rand_real, rand_real_array, rand_int64
rand_int32 calls rand_int64
rand_real calls rand_int64
rand_real_array calls rand_int64